### ISSUE TITLE
Balena push stuck after build

### ISSUE THREAD

**Issue by akarakn** [balena-io/balena-cli#1822] opened 2020-05-13 10:06 UTC
- **balena CLI version:** balena-cli-v11.33.4
- **Operating system version:**  Ubuntu 18.04, 20.04
- **32/64 bit OS and processor:** x64
- **Install method:**  standalone zip
---

I am trying to push a container to local device(RPI4) but it stucks after building phase. Do you have any idea?

log:
```[Info]    Starting build on device mydevice.local
[Info]    No "docker-compose.yml" file found at "."
[Info]    Creating default composition with source: "."
[Build]   [main] Step 1/4 : FROM balenalib/raspberrypi4-64-alpine-node
[Build]   [main]  ---> 2a5d59f69057
[Build]   [main] Step 2/4 : CMD ["cat", "/etc/os-release"]
[Build]   [main]  ---> Using cache
[Build]   [main]  ---> db9d785c83ce
[Build]   [main] Step 3/4 : LABEL io.resin.local.image=1
[Build]   [main]  ---> Using cache
[Build]   [main]  ---> f2757313900c
[Build]   [main] Step 4/4 : LABEL io.resin.local.service=main
[Build]   [main]  ---> Using cache
[Build]   [main]  ---> 6f55e0e0d5a1
[Build]   [main] Successfully built 6f55e0e0d5a1
```
DockerFile:
```
FROM balenalib/raspberrypi4-64-alpine-node
CMD ["cat", "/etc/os-release"]
```

Balena Scan:
```
Reporting scan results
- 
  host:          mydevice.local
  address:       192.168.1.23
  dockerInfo: 
    Containers:        1
    ContainersRunning: 1
    ContainersPaused:  0
    ContainersStopped: 0
    Images:            36
    Driver:            overlay2
    SystemTime:        2020-05-13T09:36:57.63534255Z
    KernelVersion:     4.19.75
    OperatingSystem:   balenaOS 2.48.0+rev1
    Architecture:      aarch64
  dockerVersion: 
    Version:    18.09.10-dev
    ApiVersion: 1.39

```

**Comment by pdcastro** [comment] 2020-05-13 15:30
@akarakn, I was not able to reproduce this issue using the same CLI version and balenaOS version (presumably a Raspberry Pi 4? I tested with an RPi4).
```
$ /mnt/data/cli/balena-cli-11.33.4/balena push 192.168.0.37
[Info]    Starting build on device 192.168.0.37
[Info]    No "docker-compose.yml" file found at "."
[Info]    Creating default composition with source: "."
[Build]   [main] Step 1/4 : FROM balenalib/raspberrypi4-64-alpine-node
[Build]   [main]  ---> 2a5d59f69057
[Build]   [main] Step 2/4 : CMD ["cat", "/etc/os-release"]
[Build]   [main]  ---> Using cache
[Build]   [main]  ---> 09426db8bc9a
[Build]   [main] Step 3/4 : LABEL io.resin.local.image=1
[Build]   [main]  ---> Using cache
[Build]   [main]  ---> ada9d12a8fca
[Build]   [main] Step 4/4 : LABEL io.resin.local.service=main
[Build]   [main]  ---> Using cache
[Build]   [main]  ---> f79cbcefae1e
[Build]   [main] Successfully built f79cbcefae1e
[Build]   [main] Successfully tagged local_image_main:latest

[Live]    Waiting for device state to settle...
[Info]    Streaming device logs...
[Live]    Watching for file changes...
[Live]    Device state settled
[Logs]    [5/13/2020, 3:17:43 PM] Restarting service 'main sha256:f79cbcefae1ecc97bc8debe08f24f4d92551db0fc61eeedd580add5ace7ab725'
[Logs]    [5/13/2020, 3:17:16 PM] [main] NAME="Alpine Linux"
[Logs]    [5/13/2020, 3:17:16 PM] [main] ID=alpine
[Logs]    [5/13/2020, 3:17:16 PM] [main] VERSION_ID=3.11.6
[Logs]    [5/13/2020, 3:17:16 PM] [main] PRETTY_NAME="Alpine Linux v3.11"
[Logs]    [5/13/2020, 3:17:16 PM] [main] HOME_URL="https://alpinelinux.org/"
[Logs]    [5/13/2020, 3:17:16 PM] [main] BUG_REPORT_URL="https://bugs.alpinelinux.org/"
[Logs]    [5/13/2020, 3:17:43 PM] [main] NAME="Alpine Linux"
[Logs]    [5/13/2020, 3:17:43 PM] [main] ID=alpine
[Logs]    [5/13/2020, 3:17:43 PM] [main] VERSION_ID=3.11.6
[Logs]    [5/13/2020, 3:17:43 PM] [main] PRETTY_NAME="Alpine Linux v3.11"
[Logs]    [5/13/2020, 3:17:43 PM] [main] HOME_URL="https://alpinelinux.org/"
[Logs]    [5/13/2020, 3:17:43 PM] [main] BUG_REPORT_URL="https://bugs.alpinelinux.org/"
[Logs]    [5/13/2020, 3:17:44 PM] Service exited 'main sha256:f79cbcefae1ecc97bc8debe08f24f4d92551db0fc61eeedd580add5ace7ab725'
```

Is it still happening for you? Be sure the device is in [local mode](https://www.balena.io/docs/learn/develop/local-mode/). From the output you shared, the `push` command got stuck at `Successfully built`. In my output above, the next step is `Successfully tagged`, which is an operation that takes place on the device, through the balena supervisor and balenaEngine. Try opening a ssh shell on the device and inspecting the containers, in case "something surprising" shows up:

```
$ balena ssh 192.168.0.37
Last login: Wed May 13 15:28:43 2020 from 192.168.0.17

root@dcbff32:~# balena-engine ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                          PORTS               NAMES
69353728de12        f79cbcefae1e                        "/usr/bin/entry.sh c…"   12 minutes ago      Restarting (0) 13 seconds ago                       main_1_1
015bdcb40fc9        balena/aarch64-supervisor:v10.8.0   "./entry.sh"             2 weeks ago         Up 19 hours (healthy)                               resin_supervisor
```

Assuming it is not a balena CLI bug, you may get additional troubleshooting help by creating a thread in the support forums: https://forums.balena.io/c/balena-cloud

**Comment by pdcastro** [comment] 2020-06-16 12:41
Closing this issue for lack of reply / activity. Feel free to add more comments even if it is closed -- I can then reopen it.

**Closed by pdcastro** 2020-06-16 12:41 UTC
Labels: support
