### ISSUE TITLE
allow specification of `docker-compose.yml` file

### ISSUE THREAD

**Issue by dt-rush** [balena-io/balena-cli#1478] opened 2019-10-18 21:38 UTC
Use-cases:

- Deploying from *one* repository to more than one application, where potentially-overlapping sets of services are desired on each of the differing applications, selected from the common set of available services in the repo 

- When one desires to: have some devices pinned to versions and not following `latest`, while deploying a specific `docker-compose.yml` (services, env vars, network settings, labels, volumes etc.) to those devices currently tracking `latest`, pinning them, deploying a different `docker-compose.yml` to others, etc.

**Comment by dt-rush** [comment] 2019-10-18 22:04
In the meantime, a workaround is to use a script to move the intended `docker-compose.yml` into place just-in-time:

```
#!/bin/bash

composefile=$1

if [ -z $composefile ]; then
    echo "needs first argument <compose file>"
    exit 1
fi

cp $composefile docker-compose.yml
echo "balena push $appName"
```

So, you'd invoke this as `./deploy.sh docker-compose-a.yml` or `./deploy.sh docker-compose-b.yml`

**Comment by pdcastro** [comment] 2019-11-25 13:09
Connects to #1142 (Add ability to select a docker-compose file)

**Comment by dt-rush** [comment] 2019-12-14 02:57
@pdcastro, i would argue this is the same and should be closed as a duplicate. What do you think?

**Comment by srlowe** [comment] 2020-01-10 14:36
Duplicate of #1142

**Closed by srlowe** 2020-01-10 14:36 UTC
Labels: type:feature
