### ISSUE TITLE
`balena preload` fails when using overlay2 storage driver

### ISSUE THREAD

**Issue by mdtusz** [balena-io/balena-cli#1377] opened 2019-08-02 18:15 UTC
- **balena CLI version:** 11.7.4
- **Operating system version:** 5.2.5-arch1-1-ARCH
- **32/64 bit OS and processor:** 64 bit
- **Install method:** AUR/yay

---

This issue has been around for quite some time, but I'd be happy to dive in and try and help solve it with some direction.

When trying to preload images from machines with the latest kernel and docker versions, AUFS is not supported so `balena preload` will fail.

```
Building Docker preloader image. [========================] 100%
| Creating preloader container
| Starting preloader container
/ Fetching application 1003317
| Reading image information
1: Step 1/7 : FROM docker:17.10.0-ce-dind
 ---> 9769e0f3f9cb
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
 ---> 78561c73fd30
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
 ---> 7b2a4755b807
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
 ---> 66f3750a880a
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
 ---> 152470dca8e3
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 83aa85398228
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
Successfully built 10499cd092fb
Successfully tagged balena/balena-preload:latest
Waiting for Docker to start...
Exception in thread background thread for pid 113:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmp18zg6_mv/docker --host=tcp://0.0.0.0:34135

  STDOUT:


  STDERR:
time="2019-08-02T18:13:31.914063304Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2019-08-02T18:13:31.914643641Z" level=info msg="libcontainerd: new containerd process, pid: 127"
Error starting daemon: error initializing graphdriver: driver not supported


Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 832, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 791, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 675, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 646, in _get_images_and_supervisor_version
    with docker_context_manager(driver, mountpoint):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 513, in docker_context_manager
    running_dockerd = start_docker_daemon(storage_driver, docker_dir)
  File "/usr/src/app/preload.py", line 482, in start_docker_daemon
    running_dockerd.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmp18zg6_mv/docker --host=tcp://0.0.0.0:34135

  STDOUT:


  STDERR:
time="2019-08-02T18:13:31.914063304Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2019-08-02T18:13:31.914643641Z" level=info msg="libcontainerd: new containerd process, pid: 127"
Error starting daemon: error initializing graphdriver: driver not supported

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

While things can likely be made to work by installing the AUFS filesystem support and sorting out the dependencies (installation from the AUR fails as of recent since `linux-aufs_friendly` is missing) , AUFS has been rejected from the mainline kernel, so it makes sense to support overlay2 - docker has changed to use overlay2 as the default driver moving forwards as well.

**Comment by imrehg** [comment] 2019-08-03 09:40
Hi, the storage driver needed is the one being used by the device type that is being preloaded, and thus the development device's (where the preload is done) need to support the balen device type's storage driver.

This is a long standing technical limitation, that we are not doing a great job showing clearly, nor handling the failure in a very transparent way.

At the moment there are some device types that are using `aufs` on balenaOS (notably the Raspberry Pi range). We are transitioning all of them to `overlay2`, likely in one of the soon upcoming releases. In the meantime, if you have a device type that uses `aufs`, you'll need to preload it on a Linux system that does support `aufs` at the moment (such as Ubuntu, e.g. run in a virtual machine, we have very good success with that).

Hope this helps, and clarifies for you what's going on!

**Comment by pdcastro** [comment] 2019-11-24 23:31
Connects to #1099 (Preload fails on macOS with error "error initializing graphdriver: driver not supported")

**Comment by mathroc** [comment] 2021-08-24 12:22
I just stumbled on this error. Looks like the raspberry pi (at least zero & 2) images still uses aufs. 

One thing to note, the balena CLI keeps waiting even though the docker container crashed so I had to looks for running containers and tail their logs to understand what went wrong

![image](https://user-images.githubusercontent.com/291531/130615117-73b568b7-fed2-4703-899f-6a46ec52a6cc.png)

> ❯ docker logs -f b88f0bc3f4f8
Waiting for Docker to start...
Exception in thread background thread for pid 114:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpc6k35djj/docker --host=tcp://0.0.0.0:36269

  STDOUT:


  STDERR:
time="2021-08-24T12:17:11.877212394Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2021-08-24T12:17:11.877648718Z" level=info msg="libcontainerd: started new docker-containerd process" pid=138
time="2021-08-24T12:17:11Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2021-08-24T12:17:11Z" level=info msg="setting subreaper..." module=containerd
time="2021-08-24T12:17:11Z" level=info msg="changing OOM score to -500" module=containerd
time="2021-08-24T12:17:11Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
tim... (3787 more, please see e.stderr)
[...]
time="2021-08-24T12:17:11Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1
time="2021-08-24T12:17:11Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1
time="2021-08-24T12:17:11Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
time="2021-08-24T12:17:11Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
time="2021-08-24T12:17:11Z" level=info msg="containerd successfully booted in 0.001939s" module=containerd
Error starting daemon: error initializing graphdriver: driver not supported

Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 954, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 910, in get_image_info
    get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 776, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 736, in _get_images_and_supervisor_version
    with docker_context_manager(driver, mountpoint):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 581, in docker_context_manager
    running_dockerd = start_docker_daemon(storage_driver, docker_dir)
  File "/usr/src/app/preload.py", line 550, in start_docker_daemon
    raise e
  File "/usr/src/app/preload.py", line 543, in start_docker_daemon
    running_dockerd.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpc6k35djj/docker --host=tcp://0.0.0.0:36269

  STDOUT:


  STDERR:
time="2021-08-24T12:17:11.877212394Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2021-08-24T12:17:11.877648718Z" level=info msg="libcontainerd: started new docker-containerd process" pid=138
time="2021-08-24T12:17:11Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2021-08-24T12:17:11Z" level=info msg="setting subreaper..." module=containerd
time="2021-08-24T12:17:11Z" level=info msg="changing OOM score to -500" module=containerd
time="2021-08-24T12:17:11Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
tim... (3787 more, please see e.stderr)
~/Projects/midi-synthetizer-autoconnect on  main is 📦 v0.1.0 via 🦀 v1.52.1 took 7s311ms

**Comment by pdcastro** [comment] 2021-08-24 13:06
@mathroc, thanks for sharing the error. Which operating system (e.g. Windows, macOS, Linux -- the machine where you were running the CLI) and which version of the balena CLI were you using?

Regarding _"the balena CLI keeps waiting even though the docker container crashed,"_ significant improvements were made in recent versions of the balena CLI, for example in versions 12.44.13, 12.44.22, 12.44.29 and 12.46.1. Try using the latest version, currently 12.47.0.

Regarding the actual error, _"error initializing graphdriver: driver not supported,"_ it will be because the device type (e.g. Raspberry Pi) requires the AUFS driver, and the driver is not available in the OS kernel. The meaning of "the OS kernel" depends on the host OS where the balena CLI is running:

* If the host OS is Linux (the machine where the CLI is running is a Linux machine), then `balena preload` should / will work as long as the AUFS kernel driver is loaded. As far as I am aware (though these things change over time), most / all Linux distros still provide kernels that contain the AUFS driver. Check these StackOverflow posts for reference:
  - https://stackoverflow.com/questions/18607200/docker-error-starting-container-unable-to-load-the-aufs-module  
`sudo apt-get install lxc wget bsdtar curl`  
`sudo apt-get install linux-image-extra-$(uname -r)`  
`sudo modprobe aufs` 
  - https://stackoverflow.com/questions/37110291/how-to-enable-aufs-on-debian 
 
* If the host OS is Windows or macOS and Docker Desktop for Windows/macOS is being used, then "the OS kernel" actually means the Linux kernel of the virtual machine used by Docker Desktop behind the scenes. In this case, the recommendation is actually to run the balena CLI on a Linux machine (or virtual machine like [VirtualBox](https://www.virtualbox.org/)), and a more specific `balena-cli` issue exists: #1099 

There is also another `balena-cli` issue specifically requesting the CLI to detect whether the AUFS driver is required but not available on the machine and, if so, dynamically print warn/error messages guiding the user regarding that the problem is and how to fix it, rather that just eventually exiting with a not very helpful message "error initializing graphdriver" buried in deep stack traces. It is issue #1633 .

Between issues #1099 and #1633, plus this comment on this issue, I think the situation is documented, so I am closing this issue in favor of those. Feel to reply on this issue though, and if needed I can reopen it.

**Closed by pdcastro** 2021-08-24 13:06 UTC
Labels: type:ux-enhancement

**Comment by mathroc** [comment] 2021-08-24 13:43
> @mathroc, thanks for sharing the error. Which operating system (e.g. Windows, macOS, Linux -- the machine where you were running the CLI) and which version of the balena CLI were you using?

I’m using Gentoo Linux, I was using balena cli 12.44.6

> 
> Regarding _"the balena CLI keeps waiting even though the docker container crashed,"_ significant improvements were made in recent versions of the balena CLI, for example in versions 12.44.13, 12.44.22, 12.44.29 and 12.46.1. Try using the latest version, currently 12.47.0.

Indeed with the latest version balena-cli stops and shows the error message :ok_hand: 

> 
> Regarding the actual error, _"error initializing graphdriver: driver not supported,"_ it will be because the device type (e.g. Raspberry Pi) requires the AUFS driver, and the driver is not available in the OS kernel. The meaning of "the OS kernel" depends on the host OS where the balena CLI is running:
> 
>     * If the host OS is Linux (the machine where the CLI is running is a Linux machine), then `balena preload` should / will work as long as the AUFS kernel driver is loaded in the host OS Linux kernel. As far as I am aware (though these things change over time), most / all Linux distros still provide kernels that contain the AUFS driver. Check these StackOverflow posts for reference:
>       
>       * https://stackoverflow.com/questions/18607200/docker-error-starting-container-unable-to-load-the-aufs-module
>         `sudo apt-get install lxc wget bsdtar curl`
>         `sudo apt-get install linux-image-extra-$(uname -r)`
>         `sudo modprobe aufs`
>       * https://stackoverflow.com/questions/37110291/how-to-enable-aufs-on-debian
> 
>     * If the host OS is Windows or macOS and Docker Desktop for Windows/macOS is being used, then "the OS kernel" actually means the Linux kernel of the virtual machine used by Docker Desktop behind the scenes. In this case, the recommendation is actually to run the balena CLI on a Linux machine (or virtual machine like [VirtualBox](https://www.virtualbox.org/)), and a more specific `balena-cli` issue exists: [Preload fails with "error initializing graphdriver: driver not supported" #1099](https://github.com/balena-io/balena-cli/issues/1099)
> 
> 
> There is also another `balena-cli` issue specifically requesting the CLI to detect whether the AUFS driver is required but not available on the machine and, if so, dynamically print warn/error messages guiding the user regarding that the problem is and how to fix it, rather that just eventually exiting with a not very helpful message "error initializing graphdriver" buried in deep stack traces. It is issue #1633 .
> 
> Between issues #1099 and #1633, plus this comment on this issue, I think the situation is documented, so I am closing this issue in favor of those. Feel to reply on this issue though, and if needed I can reopen it.

I understood that I could install the aufs driver to make this work (and that’s what I’ll do). I still commented on the issue because of this info from @imrehg:

> At the moment there are some device types that are using aufs on balenaOS (notably the Raspberry Pi range). We are transitioning all of them to overlay2, likely in one of the soon upcoming releases

It’s from 2 years ago so maybe this has been canceled ?

**Comment by klutchell** [comment] 2021-08-24 13:49
> At the moment there are some device types that are using aufs on balenaOS (notably the Raspberry Pi range). We are transitioning all of them to overlay2, likely in one of the soon upcoming releases

"Soon" might have been an exaggeration as we are still testing the migration patterns, but it is definitely still something we are actively working on and looking forward to releasing. Just changing the default storage type is relatively easy, but migrating existing devices in a safe, recoverable way without data loss is another story.
