### ISSUE TITLE
`balena version` responds immediately but hangs around for a long time

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1436] opened 2019-09-16 19:23 UTC
- **balena CLI version:** 11.10.0
- **Operating system version:** arch linux
- **Install method:** built from source
---
When running `balena version`, the command often takes 10-15s to exit (despite returning the version almost immediately).

```
❯ time (balena version)
11.10.0
( balena version; )  0.81s user 0.16s system 7% cpu 12.903 total
```

some strace excerpts (note the second column is the UNIX timestamp):
```
❯ grep 11.10.0 /tmp/out
36479 1568661225.566967 write(9, "11.10.0\n", 8) = 8
...
❯ tail -n5 /tmp/out 
36479 1568661239.276583 munmap(0x7fc9f07d1000, 8392704) = 0
36479 1568661239.276704 exit_group(0)   = ?
36484 1568661239.276743 <... futex resumed>) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
36484 1568661239.279709 +++ exited with 0 +++
36479 1568661239.279722 +++ exited with 0 +++
...
36495 1568661225.587894 close(12)       = 0
36495 1568661225.587921 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 12
36495 1568661225.587953 fstat(12, {st_mode=S_IFREG|0644, st_size=291, ...}) = 0
36495 1568661225.587986 read(12,  <unfinished ...>
36479 1568661225.587996 epoll_pwait(3,  <unfinished ...>
36495 1568661225.588001 <... read resumed>"# Name Service Switch configurat"..., 4096) = 291
36479 1568661225.588011 <... epoll_pwait resumed>[], 1024, 0, NULL, 8) = 0
36495 1568661225.588022 read(12,  <unfinished ...>
36479 1568661225.588026 epoll_pwait(3,  <unfinished ...>
36495 1568661225.588034 <... read resumed>"", 4096) = 0
36495 1568661225.588045 close(12)       = 0
36495 1568661225.588068 stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=80, ...}) = 0
36495 1568661225.588094 openat(AT_FDCWD, "/etc/host.conf", O_RDONLY|O_CLOEXEC) = 12
36495 1568661225.588117 fstat(12, {st_mode=S_IFREG|0644, st_size=73, ...}) = 0
36495 1568661225.588141 read(12, "# Resolver configuration file.\n#"..., 4096) = 73
36495 1568661225.588165 read(12, "", 4096) = 0
36495 1568661225.588186 close(12)       = 0
36495 1568661225.588208 futex(0x7fca23257424, FUTEX_WAKE_PRIVATE, 2147483647) = 0
36495 1568661225.588230 openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 12
36495 1568661225.588252 fstat(12, {st_mode=S_IFREG|0644, st_size=80, ...}) = 0
36495 1568661225.588275 read(12, "# Generated by resolvconf\ndomain"..., 4096) = 80
36495 1568661225.588301 read(12, "", 4096) = 0
36495 1568661225.588323 close(12)       = 0
```

It appears from the strace that the command is waiting on a network socket to return, or perhaps timing out waiting. This slowdown in and of itself isn't a massively important bug, but maybe highlights something else wonky with the project.

**Comment by pdcastro** [comment] 2019-09-16 22:37
@xginn8, about 1-2 second delay is common, 10-15s means something is wrong. I've tested versions 11.10.0 and 11.11.0 on macOS and could not reproduce it. But if the issue is consistently reproducible and you feel like debugging it a bit further, and given you said you're compiling from source, I can suggest a couple of things to try:

* Add a `return;` statement at the top of the following `trackCommand()` function, which will bypass [mixpanel](https://mixpanel.com/) command usage tracking:
https://github.com/balena-io/balena-cli/blob/v11.11.0/lib/events.ts#L35-L68

* Comment out the following `setupRaven();` line, which will skip error reporting via [sentry.io](https://sentry.io/):
https://github.com/balena-io/balena-cli/blob/v11.11.0/lib/app-common.ts#L94

Do one change at a time, to find out which one is the culprit. Sentry and Mixpanel are the two services that usually cause a small delay before the CLI exits. There's room for improvement there.

**Comment by hedss** [comment] 2019-09-23 09:24
@xginn8 @pdcastro This is something ideally we can actually make optional. I say this because our last OnPrem customers became quite dismayed by the 10-15 second timeout, given the external endpoints required were not available.

**Comment by pdcastro** [comment] 2019-09-23 12:35
> This is something ideally we can actually make optional

@hedss, what should be optional? We need to find out exactly where the 10-15s delay is coming from (is it Mixpanel? is it Sentry? neither?) and fix it as a bug, as it should not happen to anyone under any circumstances. For example, there is a [.timeout(100) line in events.ts](https://github.com/balena-io/balena-cli/blob/v11.11.3/lib/events.ts#L66) that, I believe, should give up waiting on the mixpanel server if it does not reply within 100ms. I couldn't reproduce the issue but if it's reproducible, I've given @xginn8 a couple of debugging suggestions to try and narrow down the problem.

**Comment by hedss** [comment] 2019-09-27 12:51
@pdcastro I think it could be either of these, and additionally it *used* to try and check to see if there was an update for itself every once in a while, which could also cause issues.

**Comment by pdcastro** [comment] 2019-12-20 14:56
> As part of each command execution there's (a) a whoami call to the api, the results of which are then used as part of (b) a call to mixpanel.

@srlowe, just a thought (not a new one, but not written down, easy to forget...) Even if just to avoid the annoying 1 or 2-second delay before the CLI exits in "normal conditions" (e.g., `balena version` prints the version, ***and then*** hangs for 1 or 2 seconds), what if the CLI forked the process early on\* with a detached child process ([spawn](https://nodejs.org/docs/latest-v8.x/api/child_process.html) "options.detached", "subprocess.unref()"), and then only the background child process was responsible for completing the mixpanel call? _Assuming mixpanel is what causes the delay..._

\* "Early on" might mean just _after_ the `whoami` result is received, assuming the `whoami` result is used / required by the foreground process as well, or well _before_ the `whoami` call, if the foreground process does not require the result.

The general plan of "caching `whoami` results and fixing the mixpanel timeout" is a fine one, though. 👍

**Comment by srlowe** [comment] 2019-12-20 15:22
@pdcastro Right, that would be a nice solution. However I suspected that the parent process would wait for the child process to exit, before existing itself, and unfortunately just confirmed this with a test case:

```
const { spawn } = require('child_process');
const child = spawn('sleep', ['3']);
```
I don't know any way of spawning a kind of 'orphaned' process.

**Comment by srlowe** [comment] 2019-12-20 15:45
@pdcastro By the way, after thinking about this more, I decided not to rush in with my original idea.  There's already some level of username caching in the SDK, and it would be good not to introduce too much complexity.  I think there may be a few different approaches.  

E.g. Another possible approach:  Since the `mixpanel` request is being proxied through the API (ie. both the `whoami` and `mixpanel` requests go to the API), a nice solution might be:
 
Change the API behaviour for the `mixpanel`  route, so that: 
1. if  `username` is not present in the request, the API will look this up itself (as the `whoami` route does).   This means we can omit the `whoami` request (though we can still attach the `username` if it's cached in the SDK.)
2. the route immediately returns a response to the client, before any of the processing has completed, which would mean that the mixpanel associated stuff would be almost imperceptible to the CLI user.  (We would not normally be able to do this, but it seems to me that we don't care what the result of this operation is, or whether it completed successfully, and so can just assume it worked.)

**Comment by pdcastro** [comment] 2019-12-20 17:10
Continuing the discussion on Flowdock:
https://www.flowdock.com/app/rulemotion/resin-frontend/threads/KEeQLaoiZT-h5hSmVsNOXN2BFPa

**Comment by srlowe** [comment] 2020-06-24 14:37
Closing, as a couple of PRs have recently addressed this (though there may be more gains found in the future): 
https://github.com/balena-io/balena-cli/pull/1884
https://github.com/balena-io/balena-api/pull/2575

**Closed by srlowe** 2020-06-24 14:37 UTC
Labels: type:bug
