### ISSUE TITLE
docker-compose.yml is being rejected by balena build

### ISSUE THREAD

**Issue by mschm** [balena-io/balena-cli#1096] opened 2019-02-11 20:10 UTC
- **Cli version: 9.12.2**
- **Standalone install: no**
- **Node version: 11.1.0**
- **Npm version: 6.4.1**
- **Operating system and architecture: macOS**

---

``` bash
$ balena build -a my-app
[Info]    Compose file detected
[Error]   Build failed
data/services/my-container/networks should be array, data/services/my-container/networks/my-network should be object, data/services/my-container/networks/my-network should be null, data/services/my-container/networks/my-network should match exactly one schema in oneOf, data/services/my-container/networks should match exactly one schema in oneOf
```

with docker-compose.yml

``` yaml
version: '2.1'
services:
  my-container:
    image: alpine
    networks:
      my-network: null
```

Checking it against [config_schema_v2.1.json](https://github.com/balena-io-modules/resin-compose-parse/blob/master/src/schemas/config_schema_v2.1.json) at https://www.jsonschemavalidator.net returns _valid_, therefore I didn't expect this behavior.

**Comment by mschm** [comment] 2019-02-12 17:13
same behavior in a different environment

- **Cli version: 9.12.2**
- **Standalone install: no**
- **Node version: 8.15.0**
- **Npm version: 6.4.1**
- **Operating system and architecture: Ubuntu 16.04.5 (x86)**

**Comment by mschm** [comment] 2019-03-01 18:24
The error disappears after changing `docker-compose.yml` to
```yaml
version: '2.0'
```

**Comment by pdcastro** [comment] 2019-11-22 18:40
@mschm, it looks like this issue fell through the cracks, and no one replied to it at the time -- sorry for that. I was testing it now, using CLI v11.18.3 (on macOS) -- a lot changed since v9.12.2, so my results may be a bit different for this reason. What I found is that the `version` field value '2', '2.0' or '2.1' made no difference, and the key to reproduce the error you were getting is the `networks` field, as follows.

This works:
```
version: '2.1'
services:
  my-container:
    image: alpine
    networks:
      - my-network
```
This does not work:
```
version: '2.1'
services:
  my-container:
    image: alpine
    networks:
      my-network: null
```
What happens, I gather, is that balena effectively supports a subset of the docker-compose 2.1 format / fields, as documented on this page:
https://www.balena.io/docs/reference/supervisor/docker-compose/

For the `networks` field, the documentation says that it _"only supports specifying network names,"_ which I think matches what I observed above. I understand this restriction comes from the fact that the on-device [balena supervisor](https://github.com/balena-io/balena-supervisor/blob/master/README.md) actively manages the network settings of application containers, and the implementation is limited. If you find that this restricts what you were trying to achieve, [an issue in the balena-io/balena-supervisor](https://github.com/balena-io/balena-supervisor/issues) repo would be a good place to report it. Or, perhaps best, creating a thread in the [balenaCloud forum](https://forums.balena.io/c/balena-cloud), which is monitored by the balena support team and would allow a wider discussion to take place.

I am closing this CLI issue with the understanding that it has been clarified, but please feel free to reply and I will be happy to reopen it as needed. Thank you for reporting it.

**Closed by pdcastro** 2019-11-22 18:40 UTC
Labels: needs investigation
