### ISSUE TITLE
Balena push failing with error: No such file or directory

### ISSUE THREAD

**Issue by Rezenders** [balena-io/balena-cli#1321] opened 2019-06-20 23:16 UTC
- **balena CLI version:** 11.3.3
- **Operating system version:** archlinux
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** zip

---
Trying to push an image to a raspberry pi 3 in local mode with:

```
$ balena push 150.162.53.10
```
And I`m getting the following error:
```
[Info]    Starting build on device 150.162.53.10
[Info]    Creating default composition with source: .
No such file or directory: /home/gus/Documents/git/jason-ros/jason_ws/src/CMakeLists.txt

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

```
Checked and the file exists

```
$ ls -la  /home/gus/Documents/git/jason-ros/jason_ws/src/
total 4
drwxr-xr-x 1 gus gus 66 abr  1 12:31 .
drwxr-xr-x 1 gus gus 50 abr  1 12:31 ..
lrwxrwxrwx 1 gus gus 50 abr  1 12:31 CMakeLists.txt -> /opt/ros/melodic/share/catkin/cmake/toplevel.cmake
drwxr-xr-x 1 gus gus 56 abr  1 12:31 hw_bridge
drwxr-xr-x 1 gus gus 56 abr  1 12:31 jason_msgs

```

**Comment by pdcastro** [comment] 2019-06-21 11:03
Thanks for reporting this issue. I'm thinking of two possibilities:
* The `CMakeLists.txt` soft links points outside Docker's build context (search for "context" in this [docker build documentation](https://docs.docker.com/engine/reference/commandline/build/)), but this is not supported by Docker or balenaEngine (see this [StackOverflow post](https://stackoverflow.com/questions/31881904/docker-follow-symlink-outside-context)).
* And/or, `balena push` is pushing the soft link itself, rather than the file it points to, but `/opt/.../toplevel.cmake` does not exist on the target device.

A test to find out whether some of the above applies would be to replace the soft link with a copy of the file:
```
# on the source machine
$ rm CMakeLists.txt
$ cp "/opt/ros/melodic/share/catkin/cmake/toplevel.cmake" CMakeLists.txt
$ balena push 150.162.53.10
```
I would expect that soft links work when pointing inside the build context, but not when pointing outside it (but I haven't recently tested this). If you share the results, we can continue the investigation from there. Thanks again.

**Comment by pdcastro** [comment] 2019-07-07 13:13
Related to issue #1169 (`balena push` should preserve symlinks)

**Comment by srlowe** [comment] 2019-10-31 12:29
@pdcastro Related issue is closed - should this also be closed?

**Comment by pdcastro** [comment] 2019-11-24 00:36
Closing this issue as we could not reproduce it, despite trying. We suspect a file permission issue on the reporter's computer. If you are still facing this issue, leave a comment and we will reopen the issue and investigate it further.

**Closed by pdcastro** 2019-11-24 00:36 UTC
Labels: can't reproduce
