### ISSUE TITLE
Balena preload error

### ISSUE THREAD

**Issue by tintinp** [balena-io/balena-cli#1008] opened 2018-10-31 21:42 UTC
I'm using node v10.13.0, npm v6.4.1, installed with
`npm install balena-cli -g --production --unsafe-perm` on ubuntu 18.04.

I looked at https://github.com/balena-io/balena-cli/issues/878 issue but having a slightly different issue.

 I'm seeing this problem and not sure how to solve it. Thank you in advance.

```Building Docker preloader image. [===                     ] 12%
Step 1/7 : FROM docker:17.10.0-ce-dind
Building Docker preloader image. [======                  ] 25%
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
Building Docker preloader image. [=========               ] 37%
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
Building Docker preloader image. [============            ] 50%
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
Building Docker preloader image. [===============         ] 62%
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
Building Docker preloader image. [==================      ] 75%
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
Building Docker preloader image. [=====================   ] 87%
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> be8635137249
Successfully built be8635137249
Building Docker preloader image. [========================] 100%



\ Creating preloader container
- Starting preloader container
/ Fetching application 1252660
| Reading image informationTraceback (most recent call last):
  File "/usr/src/app/preload.py", line 821, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 781, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 663, in get_images_and_supervisor_version
    inner_image_path = get_inner_image_path(mountpoint)
  File "/usr/src/app/preload.py", line 621, in get_inner_image_path
    device_type = get_device_type()
  File "/usr/src/app/preload.py", line 601, in get_device_type
    result = get_json("flash-boot", "device-type.json", image=image)
  File "/usr/src/app/preload.py", line 590, in get_json
    with part.mount_context_manager() as mountpoint:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 103, in mount_context_manager
    with losetup_context_manager(image, offset, size) as device:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 87, in losetup_context_manager
    device = losetup(*args).stdout.decode("utf8").strip()
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /sbin/losetup -f --show --offset 50331648 --sizelimit 83886080 /img/balena.img

  STDOUT:


  STDERR:
losetup: /img/balena.img: failed to set up loop device: No such file or directory
```

_Originally posted by @tintinp in https://github.com/balena-io/balena-cli/issues/878#issuecomment-434856487_

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_f10r)

**Comment by zvin** [comment] 2018-11-01 12:10
@tintinp which command did you used to preload?

**Comment by tintinp** [comment] 2018-11-01 17:38
@zvin I used `DEBUG=1 balena preload ./balena.img --app 1252660`

**Comment by zvin** [comment] 2018-11-06 14:05
@tintinp I was unable to reproduce this issue.
Could you please try the following on your computer in the same folder from which you tried preloading:
```sh
losetup -f --show --offset 50331648 --sizelimit 83886080 ./balena.img
```

**Comment by tintinp** [comment] 2018-11-06 20:04
@zvin thanks, this is the output I got

`losetup: cannot find an unused loop device`

So, I run it with sudo

`sudo losetup -f --show --offset 50331648 --sizelimit 83886080 ./balena.img`

and got this output

`/dev/loop15`

**Comment by zvin** [comment] 2018-11-07 10:17
@tintinp it looks like it works.
Could you try the same in the preloader docker image:
```sh
docker run --privileged --rm --mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img --entrypoint "/sbin/losetup" resin/resin-preload -f --show -offset 50331648 --sizelimit 83886080 /img/balena.img
```

**Comment by tintinp** [comment] 2018-11-07 19:08
sometimes, I'll get this output
`losetup: /img/balena.img: failed to set up loop device: No such file or directory`
and sometimes
`/dev/loop16`

Sorry I don't really know the inner function of preload but why is it trying to use `/img/` directory?

**Comment by zvin** [comment] 2018-11-08 08:29
@tintinp the image is bind mounted to /img/balena.img in the docker container (see the `--mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img` option) so that's perfectly normal.

What are the other /dev/loop[0-15] loop devices for?
Does it work better if you remove them (`sudo losetup -D`) ?

**Comment by tintinp** [comment] 2018-11-08 18:41
@zvin  /dev/loop[0-15] are already there when booted, I tried running as root and got `losetup -f --show --offset 50331648 --sizelimit 83886080 ./balena.img` to work without using `sudo` so I tried running `DEBUG=1 balena preload ./balena.img --app $APP_ID` as root. However, I still get the same message error message
```
RAN: /sbin/losetup -f --show --offset 4194304 --sizelimit 4194304 /img/balena.img

  STDOUT:


  STDERR:
losetup: /img/balena.img: failed to set up loop device: No such file or directory
```

**Comment by zvin** [comment] 2018-11-08 18:51
To clarify, running things with `sudo` or as root is the same.
You do not need to run docker commands as root as you're only communicating with the docker daemon that runs with the required privileges.

What does `sudo losetup -l` show on the host?
Which image are you preloading? The last error you sent seems weird to me (`RAN: /sbin/losetup -f --show --offset 4194304 --sizelimit 4194304 /img/balena.img`). The 4kb sizelimit seems strange. Is it a copy paste error?
Which version of Docker are you using (run `docker version`) ?

**Comment by zvin** [comment] 2018-11-08 18:55
I think the `No such file or directory` refers to the loop device and not to the image itself
We can check this by running
```
docker run --privileged --rm --mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img --entrypoint "/bin/ls" resin/resin-preload -l /img/balena.img
```

**Comment by tintinp** [comment] 2018-11-08 19:01
I'm running Docker version 18.06.1-ce, build e68fc7a

This is the output when ran `sudo losetup -l`

```
NAME SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                         DIO LOG-SEC
/dev/loop1
             0      0         1  1 /var/lib/snapd/snaps/gnome-characters_103.snap
                                                                       0     512
/dev/loop8
             0      0         1  1 /var/lib/snapd/snaps/gnome-3-26-1604_70.snap
                                                                       0     512
/dev/loop6
             0      0         1  1 /var/lib/snapd/snaps/core_4917.snap
                                                                       0     512
/dev/loop13
             0      0         1  1 /var/lib/snapd/snaps/gnome-calculator_260.snap
                                                                       0     512
/dev/loop4
             0      0         1  1 /var/lib/snapd/snaps/gtk-common-themes_319.snap
                                                                       0     512
/dev/loop11
             0      0         1  1 /var/lib/snapd/snaps/core_5742.snap
                                                                       0     512
/dev/loop2
             0      0         1  1 /var/lib/snapd/snaps/gnome-3-26-1604_74.snap
                                                                       0     512
/dev/loop0
             0      0         1  1 /var/lib/snapd/snaps/gtk-common-themes_701.snap
                                                                       0     512
/dev/loop9
             0      0         1  1 /var/lib/snapd/snaps/gnome-system-monitor_57.snap
                                                                       0     512
/dev/loop7
             0      0         1  1 /var/lib/snapd/snaps/gnome-logs_37.snap
                                                                       0     512
/dev/loop5
             0      0         1  1 /var/lib/snapd/snaps/gnome-system-monitor_51.snap
                                                                       0     512
/dev/loop12
             0      0         1  1 /var/lib/snapd/snaps/gnome-calculator_180.snap
                                                                       0     512
/dev/loop3
             0      0         1  1 /var/lib/snapd/snaps/gnome-logs_45.snap
                                                                       0     512
/dev/loop10
             0      0         1  1 /var/lib/snapd/snaps/gnome-characters_139.snap
                                                                       0     512
```
when I run the docker command above, I got this,

`-rw-r--r--    1 1000     1000     3296722944 Nov  8 18:31 /img/balena.img`

**Comment by zvin** [comment] 2018-11-08 19:03
`-rw-r--r-- 1 1000 1000 3296722944 Nov 8 18:31 /img/balena.img` means the image is there. So the `No such file or directory` error is about the loop device.
Which image are you trying to preload?

**Comment by tintinp** [comment] 2018-11-08 19:10
sorry I forgot to answer that, I'm trying to preload SKX2 v2.9.7+rev4 image

**Comment by zvin** [comment] 2018-11-08 19:31
Can you please try this one (it sleeps for one second before using `losetup`):
```sh
docker run --privileged --rm --mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img --entrypoint "/bin/sh" resin/resin-preload -c "sleep 1 && /sbin/losetup -f --show --offset 50331648 --sizelimit 83886080 /img/balena.img"
```
Does it work all the time or does it also alternate between working and not working?

**Comment by tintinp** [comment] 2018-11-08 19:33
It still alternates between working and not working.

**Comment by zvin** [comment] 2018-11-08 19:57
Does the `ls` command alternate too?
```sh
docker run --privileged --rm --mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img --entrypoint "/bin/ls" resin/resin-preload -l /img/balena.img
```

**Comment by tintinp** [comment] 2018-11-08 20:12
Nope it doens't

**Comment by zvin** [comment] 2018-11-08 20:16
If you want to run some quick checks, you can open an interactive terminal inside the container with this command:
```
docker run -it --privileged --rm --mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img --entrypoint "/bin/sh" resin/resin-preload
```

**Comment by zvin** [comment] 2018-11-08 20:18
Could you try running `losetup -f`several times in the container? (use the command in the comment above) to get shell inside the container).

**Comment by tintinp** [comment] 2018-11-08 20:22
Yep, this works

```
~/Downloads$  docker run -it --privileged --rm --mount type=bind,source=$(readlink -f ./balena.img),target=/img/balena.img --entrypoint "/bin/sh" resin/resin-preload
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup -f
/dev/loop22
```

**Comment by zvin** [comment] 2018-11-08 20:28
Could you then try `losetup -f` then `losetup <the value returned by losetup -f> /img/balena.img` several times ?

**Comment by tintinp** [comment] 2018-11-08 20:36
After `losetup -f` returned `/dev/loop22`, then run `losetup /dev/loop22 /img/balena.img` and that returned no output. The next time I run it, it said resource busy.
```
/usr/src/app # losetup -f
/dev/loop22
/usr/src/app # losetup /dev/loop22 /img/balena.img
/usr/src/app # losetup /dev/loop22 /img/balena.img
losetup: /img/balena.img: failed to set up loop device: Resource busy
/usr/src/app # losetup /dev/loop22 /img/balena.img
losetup: /img/balena.img: failed to set up loop device: Resource busy
/usr/src/app # losetup /dev/loop22 /img/balena.img
losetup: /img/balena.img: failed to set up loop device: Resource busy
/usr/src/app # losetup /dev/loop22 /img/balena.img
```

**Comment by zvin** [comment] 2018-11-08 20:38
Sorry, there's a misunderstanding here.
I mean run `losetup -f` then `losetup <the value returned by losetup -f> /img/balena.img ` then start over at `losetup -f`.

**Comment by tintinp** [comment] 2018-11-08 20:41
it worked the first time I run it, then failed the next time
```
usr/src/app # losetup -f
/dev/loop24
/usr/src/app # losetup /dev/loop24 /img/balena.img
/usr/src/app # losetup -f
/dev/loop25
/usr/src/app # losetup /dev/loop25 /img/balena.img
losetup: /dev/loop25: failed to set up loop device: No such file or directory
/usr/src/app # losetup -f
/dev/loop25
/usr/src/app # losetup /dev/loop25 /img/balena.img
losetup: /dev/loop25: failed to set up loop device: No such file or directory
```

**Comment by zvin** [comment] 2018-11-08 20:48
Oo
This is really weird.

Could you try installing `strace` with `apk add strace` in the container and try `strace losetup /dev/loop25 /img/balena.img` ?

**Comment by tintinp** [comment] 2018-11-08 20:54
```
/usr/src/app # losetup -f
/dev/loop26

/usr/src/app # strace losetup /dev/loop26 /img/balena.img 
execve("/sbin/losetup", ["losetup", "/dev/loop26", "/img/balena.img"], [/* 9 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7f2903341b48) = 0
set_tid_address(0x7f2903341b80)         = 15
open("/etc/ld-musl-x86_64.path", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libsmartcols.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=132968, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340Y\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2236416, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f2902e94000
mmap(0x7f29030b3000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1f000) = 0x7f29030b3000
mmap(0x7f29030b5000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f29030b5000
close(3)                                = 0
mprotect(0x7f29030b3000, 4096, PROT_READ) = 0
mprotect(0x7f290333e000, 4096, PROT_READ) = 0
mprotect(0x5567eccc8000, 4096, PROT_READ) = 0
stat("/sys/block", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
uname({sysname="Linux", nodename="a06868b0dd72", ...}) = 0
stat("/dev/loop-control", {st_mode=S_IFCHR|0660, st_rdev=makedev(10, 237), ...}) = 0
stat("/dev/loop26", {st_mode=S_IFBLK|0660, st_rdev=makedev(7, 26), ...}) = 0
open("/img/balena.img", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_PATH) = 3
readlink("/proc/self/fd/3", "/img/balena.img", 4095) = 15
fstat(3, {st_mode=S_IFREG|0644, st_size=3296722944, ...}) = 0
stat("/img/balena.img", {st_mode=S_IFREG|0644, st_size=3296722944, ...}) = 0
close(3)                                = 0
open("/img/balena.img", O_RDWR|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
open("/dev/loop26", O_RDWR|O_CLOEXEC)   = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
ioctl(4, LOOP_SET_FD, 3)                = 0
ioctl(4, LOOP_SET_STATUS64, {lo_offset=0, lo_number=0, lo_flags=0, lo_file_name="/img/balena.img", ...}) = 0
close(3)                                = 0
stat("/img/balena.img", {st_mode=S_IFREG|0644, st_size=3296722944, ...}) = 0
close(4)                                = 0
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by tintinp** [comment] 2018-11-08 20:56
and the when I run it again, this happened
```
/usr/src/app # losetup -f
/dev/loop27
/usr/src/app # strace losetup /dev/loop27 /img/balena.img 
execve("/sbin/losetup", ["losetup", "/dev/loop27", "/img/balena.img"], [/* 9 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7f8e21c61b48) = 0
set_tid_address(0x7f8e21c61b80)         = 19
open("/etc/ld-musl-x86_64.path", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libsmartcols.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=132968, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340Y\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2236416, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f8e217b4000
mmap(0x7f8e219d3000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x1f000) = 0x7f8e219d3000
mmap(0x7f8e219d5000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8e219d5000
close(3)                                = 0
mprotect(0x7f8e219d3000, 4096, PROT_READ) = 0
mprotect(0x7f8e21c5e000, 4096, PROT_READ) = 0
mprotect(0x55a286183000, 4096, PROT_READ) = 0
stat("/sys/block", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
uname({sysname="Linux", nodename="a06868b0dd72", ...}) = 0
stat("/dev/loop-control", {st_mode=S_IFCHR|0660, st_rdev=makedev(10, 237), ...}) = 0
stat("/dev/loop27", 0x7ffcf8d887f8)     = -1 ENOENT (No such file or directory)
open("/dev/loop-control", O_RDWR|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
ioctl(3, LOOP_CTL_ADD, 27)              = -1 EEXIST (File exists)
close(3)                                = 0
open("/img/balena.img", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_PATH) = 3
readlink("/proc/self/fd/3", "/img/balena.img", 4095) = 15
fstat(3, {st_mode=S_IFREG|0644, st_size=3296722944, ...}) = 0
stat("/img/balena.img", {st_mode=S_IFREG|0644, st_size=3296722944, ...}) = 0
close(3)                                = 0
open("/img/balena.img", O_RDWR|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
open("/dev/loop27", O_RDWR|O_CLOEXEC)   = -1 ENOENT (No such file or directory)
close(3)                                = 0
open("/dev/loop27", O_RDWR|O_CLOEXEC)   = -1 ENOENT (No such file or directory)
writev(2, [{iov_base="losetup: ", iov_len=9}, {iov_base=NULL, iov_len=0}], 2losetup: ) = 9
writev(2, [{iov_base="/dev/loop27: failed to set up lo"..., iov_len=41}, {iov_base=NULL, iov_len=0}], 2/dev/loop27: failed to set up loop device) = 41
writev(2, [{iov_base="", iov_len=0}, {iov_base=": ", iov_len=2}], 2: ) = 2
writev(2, [{iov_base="", iov_len=0}, {iov_base="No such file or directory", iov_len=25}], 2No such file or directory) = 25
writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2
) = 1
close(1)                                = 0
close(2)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by zvin** [comment] 2018-11-08 20:57
Do you see a `loop27` device if you run `ls /dev/loop*`

**Comment by tintinp** [comment] 2018-11-08 20:59
I don't see it in the container, however, I see it outside the container though

**Comment by zvin** [comment] 2018-11-08 21:08
This looks like a docker bug then. This one probably https://github.com/moby/moby/issues/27886 . Not sure what to do next.
I guess running `mknod -m640 /dev/loop27 b 7 27` before `losetup /dev/loop27 /img/balena.img`may work around it here but we need to investigate further.

**Comment by zvin** [comment] 2018-11-08 21:13
Could you try one last thing (I took it from one of the comments in the docker issue): quit the shell inside the container, then start it again bind-mounting `/dev` inside the container:
```sh
docker run -it --privileged --rm -v /dev:/dev -v $(readlink -f ./balena.img):/img/balena.img --entrypoint "/bin/sh" resin/resin-preload
```
then retry the `losetup -f` then `losetup /dev/loopX /img/balena.img` thing from above.

**Comment by tintinp** [comment] 2018-11-08 21:18
Oh I see, yes that worked well

```
/usr/src/app # losetup -f
/dev/loop27
/usr/src/app # losetup /dev/loop27 /img/balena.img 
/usr/src/app # losetup -f
/dev/loop28
/usr/src/app # losetup /dev/loop28 /img/balena.img 
/usr/src/app # losetup -f
/dev/loop29
/usr/src/app # losetup /dev/loop29 /img/balena.img 
/usr/src/app # 
```

**Comment by zvin** [comment] 2018-11-08 21:20
Excellent, I'll update resin-preload to do the same.

**Comment by zvin** [comment] 2018-11-08 21:30
Thank you for helping me debug this. The issue was not appearing on my computer so I wouldn't be able to debug it by myself.
If not today, a fix will probably be released on Monday, I'll ping you.

**Comment by tintinp** [comment] 2018-11-08 21:45
Awesome, thanks!

**Comment by zvin** [comment] 2018-11-09 05:13
@tintinp balena-preload 8.0.1 was just published on npm, it'll be installed if you reinstall balena-cli https://www.npmjs.com/package/balena-cli

**Comment by thgreasi** [comment] 2018-11-12 08:56
@tintinp did you have the chance to try this out?
Does the new preload version fix the issue for you?

**Comment by tintinp** [comment] 2018-11-12 18:01
@zvin @thgreasi, thank you for your help. The fix works, although I encounter another problem in the later stage of the preload. I'm not sure if I should continue on this tread but for now I will post it here.

```
\ Reading image informationWaiting for Docker to start...
| Reading image informationDocker started
- Reading image information
? Select a release latest
- Resizing partitions and waiting for dockerd to startResizing ext4 filesystem of partition n°13 of /img/balena.img using /dev/loop16
\ Resizing partitions and waiting for dockerd to startFile system OK
\ Resizing partitions and waiting for dockerd to startTraceback (most recent call last):
  File "/usr/src/app/preload.py", line 821, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 766, in main_preload
    mountpoint + "/etc/resin-device-pinning.conf"
  File "/usr/src/app/preload.py", line 521, in write_resin_device_pinning
    if not app_data.get("pinDevice", False):
AttributeError: 'list' object has no attribute 'get'
\ Resizing partitions and waiting for dockerd to start
```

I tried with another computer and also have the same issue. Sorry for the long running tread.

**Comment by zvin** [comment] 2018-11-12 19:16
@tintinp this is a separate issue, I'll fix it quickly.
Closing this one.

**Closed by zvin** 2018-11-12 19:16 UTC

**Comment by tintinp** [comment] 2018-11-12 19:33
Thank you

**Comment by zvin** [comment] 2018-11-12 19:55
@tintinp you can fix this by omitting the `-p` flag you're passing to `balena preload` or by using a newer skx2 image. Yours has a supervisor version that doesn't support pinning.
This is the fix: https://github.com/balena-io/balena-preload/pull/190 , it'll be merged soon.

**Comment by tintinp** [comment] 2018-11-12 20:30
@zvin Using new skx2 image works. Thank you, I can successfully preload now.
