### ISSUE TITLE
`balena os build-config ../path/rpi3.img raspberrypi3 --output test-config.json` results in a file that only contains 'undefined'

### ISSUE THREAD

**Issue by Oceanswave** [balena-io/balena-cli#1975] opened 2020-08-04 01:42 UTC
# Expected Behavior

The Balena CLI generates a output configuration json file that contains the configuration entered into the interactive prompts

# Actual Behavior

The .json file output contains a single line that reads 'undefined' regardless of the inputs

![image](https://user-images.githubusercontent.com/760674/89243581-4ffc3a80-d5d2-11ea-9e6e-8b856d37be1e.png)

![image](https://user-images.githubusercontent.com/760674/89243550-3eb32e00-d5d2-11ea-882c-987e5d5b803d.png)

https://github.com/balena-io/balena-cli/blob/304ade9772ec89f1631d7e6bc3b022bef3017ee0/lib/actions-oclif/os/build-config.ts#L97

currently does not return a value from buildConfig, which is why the value of 'config' in the caller always is 'undefined'
 
Additionally, it is observed that the image file indicates that it has been created successfully, rather than the value of the output argument.

https://github.com/balena-io/balena-cli/blob/304ade9772ec89f1631d7e6bc3b022bef3017ee0/lib/actions-oclif/os/build-config.ts#L94

Should probably be changed to ``` `Config file ${options.output} created successfully.` ```

# Steps to Reproduce the Problem

Follow the instructions indicated by ```balena os build-image --help``` on a downloaded image.

1. ```balena os download raspberrypi3 -o ./images/test.img```
2. ```balena os build-config ./images/test.img raspberrypi3 -o test-config.json```
3. Input any configuration - selecting 'ethernet' is the simplest route
4. Observe that the output file contains only the text 'undefined'

# Specifications

- balena-cli version "12.10.2" 
- macOS 10.15.6
- 64bit intel
- executable installer
- Node.js version "10.21.0" is reported by ```balena --version -a```

![image](https://user-images.githubusercontent.com/760674/89243530-30651200-d5d2-11ea-89bc-aee842911f60.png)

**Comment by pdcastro** [comment] 2020-08-04 16:34
@Oceanswave, many thanks for the detailed issue report -- you have practically written the PR! 👍 💯   I have merely translated your words into Typescript in PR #1978, which should be merged soon. The cause of the issue was an error in the recent conversion of `os build-config` from [Capitano](https://github.com/balena-io/capitano/) to [oclif](https://oclif.io/) in PR #1953 -- and more fundamentally, insufficient automated testing. Apologies for the trouble this has caused you. We are improving testing coverage over time though: a lot better now than a year ago, if it serves as some consolation. Thanks again. 🙏

**Closed** 2020-08-04 17:21 UTC

**Comment by Oceanswave** [comment] 2020-08-07 13:09
Thanks @pdcastro!
