### ISSUE TITLE
Balena 0.98 is invalid

### ISSUE THREAD

**Issue by BrantRoom3327** [balena-io/balena-cli#1069] opened 2019-01-09 16:12 UTC
In case someone missed the jenkins build... The 0.98 release for windows and linux is 22 bytes in size and obviously invalid.  Might be time for someone to look at the builder and fix that issue.

**Comment by pdcastro** [comment] 2019-11-18 23:51
It looks like no one replied to this issue when it was reported - sorry for that, and thank you for reporting it. 11 months later, I assume the issue is now obsolete and therefore I am closing it. Please add a comment if it is not really obsolete.

**Closed by pdcastro** 2019-11-18 23:51 UTC
