### ISSUE TITLE
Failed import of node-raspberrypi-usbboot - `MODULE_NOT_FOUND` 

### ISSUE THREAD

**Issue by mdtusz** [balena-io/balena-cli#1402] opened 2019-08-20 20:33 UTC
- **balena CLI version:** 11.8.3-1
- **Operating system version:** Arch Linux
- **32/64 bit OS and processor:** 64bit intel
- **Install method:** AUR/yay

---

### Reproduction

1. Install/update `balena-cli` (`yay` in my case)
2. `sudo balena local flash the_image.img`

### Error

```
Failed to import node-raspberrypi-usbboot: { Error: Cannot find module '/usr/lib/node_modules/balena-cli/node_modules/usb/src/binding/usb_bindings.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.resolveFilenameOptimized [as _resolveFilename] (/usr/lib/node_modules/balena-cli/node_modules/fast-boot2/index.js:57:33)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/usb/usb.js:5:38)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/node-raspberrypi-usbboot/build/index.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/etcher-sdk/build/scanner/adapters/usbboot.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/etcher-sdk/build/scanner/adapters/index.js:23:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/etcher-sdk/build/scanner/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/etcher-sdk/build/index.js:26:17)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function._load (/usr/lib/node_modules/balena-cli/node_modules/raven/lib/instrumentation/instrumentor.js:34:35)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Promise.resolve.then (/usr/lib/node_modules/balena-cli/build/actions/local/flash.js:55:86) code: 'MODULE_NOT_FOUND' }
Part of the CLI could not be loaded. This typically means your CLI install is in a broken state.
You can normally fix this by uninstalling and reinstalling the CLI.

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
``` 

The issue is present using both the `balena-cli` and `balena-cli-git` packages. Uninstalling and reinstalling after a cache clean (for both packages) fails to resolve the issue.

**Comment by pdcastro** [comment] 2019-08-20 21:00
> **Install method:** AUR/yay

I've googled it and found that [AUR/yay](https://averagelinuxuser.com/which-aur-helper-yay/) is a package manager for Arch Linux. It is not an official distribution channel for the balena CLI; check the official [installation instructions](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md). I have just tested running the balena-cli [standalone zip package](https://github.com/balena-io/balena-cli/releases) on the [archlinux/base image](https://hub.docker.com/r/archlinux/base) and at least the commands `balena login` and `balena apps` worked successfully, so I suggest you try running the standalone zip package instead of using AUR/yay.

**Comment by mdtusz** [comment] 2019-08-20 21:14
`yay` and the AUR work using package build scripts - the build for balena-cli using it is basically the same as recommended installation method.

@imrehg seems to be the maintainer - I was unsure if it was an "official" distribution for the cli. 

I'll poke around some more here though. Very possible that it's an npm issue or something else with my own installation.

**Comment by imrehg** [comment] 2019-08-22 09:08
@mdtusz yeah, I'm (one of the) maintainer(s) of [that package](https://aur.archlinux.org/packages/balena-cli/), along with @xginn8. Generally issues for AUR packages are better on AUR itself, as it more in context, but for this time, since the issue is already open, we can discuss it here (@pdcastro, will take care of this:)

As per the issue, I'm checking out `yay`, personally using [`yaourt`](https://wiki.archlinux.org/index.php?title=Yaourt&redirect=no) and that doesn't seem to have any issues. 

While we are checking with `yay`, can you try to install the package from source, ie. `makepkg -i`? See if that works correctly?

**Comment by imrehg** [comment] 2019-08-22 09:14
Actually that `balena local flash` cli function is not often exercised by me, so maybe something slipped, checking that now.

**Comment by imrehg** [comment] 2019-08-22 12:45
@mdtusz figured it out, one of the optimizations we did in the package to install only what seemed required packages, but that ended up missing some. Removed that optimization, and the package works now. The `..-git` package needed some other fixes as well, owing to recent changes to how this code is built/prepared.

Thus now `balena-cli-11.8.3-2` and `balena-cli-git-11.8.3.r0.g56aabad8-1` should be working correctly. I'll close this issue, but feel free to reopen it if it doesn't work for you for any reason!

For the future, in case of AUR packaging issues, please comment on the package on AUR first.

Cheers! :)

**Closed by imrehg** 2019-08-22 12:45 UTC

**Comment by mdtusz** [comment] 2019-08-22 14:57
Excellent! Thanks for the quick turnaround.
