### ISSUE TITLE
resin ssh issue cannot read 'app_name'

### ISSUE THREAD

**Issue by Carlos-fernandez** [balena-io/balena-cli#817] opened 2018-03-19 04:33 UTC
- **resin-cli version:**
            7.0.5
- **Operating system and architecture:**-Windows10 (Linux Bash)

Cannot read property 'app_name' of undefined

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

**Comment by pimterry** [comment] 2018-03-19 18:35
I suspect this is a duplicate of #544. @Carlos-fernandez this can happen if you end up with a device that you own, but whose application you can no longer access. The likely route to get into that state is by moving your device into an application that you're a collaborator on (not the owner), and then being removed from that application, leaving the device behind.

Does that sound like it's what's happened? Do you know the details of the device affected?

We do have some proper fixes for this coming very soon, but they involve some internal restructuring of the model to make this impossible, and I'd rather not build workarounds for it through the CLI in the meantime.

For now, I'm afraid that puts you in an awkward place. This device needs to be either deleted entirely, or moved back into an application you own. Which would you prefer?

We can fix this for you, but we'd need to confirm device ownership and details first. Can you email `pm@resin.io` from the email address associated with your resin account, with a link to this issue, and any details about the device etc you have? We'll take a closer look from there.

**Comment by pdcastro** [comment] 2019-11-22 16:49
As in issue #544, I understand that API changes were made to fix / avoid this problem, so it should not be happening anymore and I am closing this issue. If this isn't the case, just leave a comment and I will reopen the issue and investigate it further. Thanks for reporting it!

**Closed by pdcastro** 2019-11-22 16:49 UTC
Labels: priority:high, type:bug
