### ISSUE TITLE
BalenaRequestError: Request error: Some v1 endpoints are only allowed on single-container apps

### ISSUE THREAD

**Issue by josephcfk** [balena-io/balena-cli#1011] opened 2018-11-02 23:02 UTC
- **Cli version:** balena version 9.0.1
- **Operating system and architecture:** MACOS

**Comment by josephcfk** [comment] 2018-11-03 00:41
bash-3.2$ balena ssh 2c7527e557d8c28cafd0e67e91ed5dcf
Connecting to: 2c7527e557d8c28cafd0e67e91ed5dcf
BalenaRequestError: Request error: Some v1 endpoints are only allowed on single-container apps

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io

bash-3.2$ resin ssh 2c7527e557d8c28cafd0e67e91ed5dcf
ERR_BUFFER_OUT_OF_BOUNDS: Attempt to write outside buffer bounds

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

**Comment by pimterry** [comment] 2018-11-05 16:55
Yes, SSHing into applications with multiple containers with the CLI isn't well supported right now, but we are working on it.

I'm going to close this ticket as it's a duplicate of https://github.com/balena-io/balena-cli/issues/856. Fortunately though, that does include a workaround:

```bash
balena ssh <uuid> --host

# On the host:
balena-engine ps # Find the app container id
balena-engine exec -it <app-container-id> /bin/sh
```

(n.b. you may need to run `balena` instead of `balena-engine` on some older OS versions)

**Closed by pimterry** 2018-11-05 16:55 UTC
