### ISSUE TITLE
balena-cli unusable if `.balenarc.yml` is invalid

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1100] opened 2019-02-14 11:32 UTC
- **Cli version:** 9.12.2
- **Standalone install:** no

If `.balenarc.yml` becomes invalid yaml (specifically tested with the global `$HOME/.balenarc.yml`), the CLI exits immediately with only `null`. This lack of information in turn makes debugging the CLI's failure very difficult. Likely this error comes from balena-cli's settings setup [here](https://github.com/balena-io/balena-cli/blob/master/lib/app.coffee#L67), and in turn how `balena-settings-config` returns an error.

To reproduce:

```sh
❯ cp $HOME/.balenarc.yml $HOME/.balenarc.yml.bak
❯ echo "invalid yaml" > $HOME/.balenarc.yml
❯ balena version
null
```

**Comment by ffissore** [comment] 2019-11-18 09:40
Stumbled into this one just now. I was playing with the [advanced masterclass](https://github.com/balena-io-projects/balena-cli-advanced-masterclass), added the entry `balenaUrl: 'balena-staging.com'` and then commented it, to see if balena-cli could still talk to the production env

balena-cli stopped working (even `balena version` prints nothing)

Problem is [balena settings client - readConfigFile](https://github.com/balena-io-modules/balena-settings-client/blob/master/lib/settings.ts#L86), where an invalid yaml will throw an error. That function is called by [getSettings](https://github.com/balena-io-modules/balena-settings-client/blob/master/lib/settings.ts#L96) which is wrapped by a `_.once`. `getSettings` is called by [app-common setupGlobalProxy](https://github.com/balena-io/balena-cli/blob/master/lib/app-common.ts#L58) which **handles** the error by silently setting `proxy = null`.

So:
- reading settings throws an error
- first calling function handles it and does not report it
- subsequent calls to reading settings will return `undefined` because of `_.once`

My 2 cents: reading the yaml file should return an empty object, so that other settings sources will be used. Error should be returned to users as a warning

**Comment by srlowe** [comment] 2020-11-11 11:38
In latest, behaviour is:

```
❯ cp $HOME/.balenarc.yml $HOME/.balenarc.yml.bak
❯ echo "invalid yaml" > $HOME/.balenarc.yml
❯ balena version
Error parsing config file /home/scott/.balenarc.yml: Invalid YAML: invalid yaml

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```
Likely fixed by recent error handling improvements (original issue reproduced in v9).  IMO this is now correct behaviour, so closing.

**Closed by srlowe** 2020-11-11 11:38 UTC
Labels: needs investigation, type:bug

**Comment by pdcastro** [comment] 2020-11-11 12:45
> IMO this is now correct behaviour

@srlowe, indeed, except for one detail: the Yaml parsing error is reported to Sentry.io, which is not necessary. It should be made an `ExpectedError`, or included in the regex matching.
