### ISSUE TITLE
A corrupted ~/.balenarc.yml will cause the cli to not start up

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/balena-cli#1192] opened 2019-04-26 15:10 UTC
With a corrupted ~/.balenarc.yml:

```
$ DEBUG=1 balena help
null
```

- **Cli version:** 10.8.0
- **Standalone install:** no
- **Node version:** 10.10.0
- **Npm version:** 6.4.1
- **Operating system and architecture:** Arch linux x86_64

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by srlowe** [comment] 2019-10-31 11:53
Duplicate of #1100

**Closed** 2019-10-31 11:56 UTC
