### ISSUE TITLE
In the local mode, how can I assure that once the packages have been installed on the device, they won't be installed again in the subsequent push.

### ISSUE THREAD

**Issue by abhipony** [balena-io/balena-cli#1316] opened 2019-06-19 09:01 UTC
In the local mode, how can I assure that once the packages have been installed on the device, they won't be installed again in the subsequent push? 

For example, I have the command to install boost libraries in my Dockerfile.template like below
RUN apt-get -q update && apt-get install libboost-all-dev

This one installs on every push and takes a lot of time. 

Is there any way to prevent it. Please help.

**Comment by pdcastro** [comment] 2019-06-19 11:06
I wonder if it's a matter of re-arranging the Dockerfile. Check the sample `Dockerfile.template` in the following Livepush blog:

> https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/
> _The livepush process will look at the Dockerfile, and split it into groups internally. These groups have dependencies on external files, just like in Docker layer caching. If, for example, we changed the package.json file, step 3 onwards would become invalidated, but a source file change would only invalidate step 5 onwards._

Note that balena CLI version 11.x.x made some significant changes to livepush feature, so be sure to a recent version, [the latest if possible](https://github.com/balena-io/balena-cli/releases).

Balena's support team may be able to help you further. They don't monitor this GitHub repo, so please re-post this question on the balenaCloud forums: https://forums.balena.io/c/balena-cloud
When you do, please include the balena-cli command line you are using (push command-line options), the balena CLI version, the output of the push command, the balena OS version of your balena device and other information that you think may be relevant. This is important because they may attempt to reproduce the issue you are having on their own devices, for investigation. Thanks!

**Comment by pdcastro** [comment] 2019-06-21 13:37
Closing this issue with the understanding that it is not a CLI bug, and given the advice above. But feel free to reopen it as needed.

**Closed by pdcastro** 2019-06-21 13:37 UTC
