### ISSUE TITLE
`balena logs` does not work on local mode device

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#1631] opened 2020-02-25 17:41 UTC
User reports that they are not able to use `balena logs` on a local mode device device, where the cli seems stuck on the pinging state:
```
DEBUG=1 balena logs 12345678.local

[debug] original argv0="balena" argv=[/usr/local/bin/balena,/snapshot/versioned-source/bin/balena,logs,12345678.local] length=4
[Debug]   Checking we can access device
[Debug]   Sending request to http://12345678.local:48484/ping 
```

The user reports that `balena scan` & `balena push` works on the same device both when using `.local` as well as when using an ip.

The device was running balenaOS 2.46.1+rev1.

- **balena CLI version:** v11.28.2
- **Operating system version:** Ubuntu 18.04.4 LTS
- **32/64 bit OS and processor:**
- **Install method:** downloading the binary from the balena-io/balena-cli releases page

**Comment by thgreasi** [comment] 2020-02-25 18:02
See: https://jel.ly.fish/55a77735-863d-4e2f-90cc-034c92e05c25 (linking didn't work b/c of GH incident)

**Comment by AlidaOdendaal** [comment] 2020-03-02 09:36
Another user in the attached support thread has reported the same problem. They can SSH to the device using the IP address and balena scan identifies the device successfully.

Their setup is as follows:

* **balena CLI version:** 11.28.2
* **Operating system:** Mac OS 10.15.3
* **balenaOS 2.47.0+rev1**

**Comment by pdcastro** [comment] 2020-03-03 00:21
So far I cannot reproduce it. Tested with:
* CLI v11.28.2 (zip install), Ubuntu 18.04, balenaOS 2.46.1+rev1, RPi 3
* CLI v11.28.2 (zip install), Ubuntu 18.04, balenaOS 2.47.0+rev1, RPi 4
* CLI v11.28.2 (zip install), macOS 10.14.6, balenaOS 2.46.1+rev1, RPi 3
* CLI v11.28.2 (zip install), macOS 10.14.6, balenaOS 2.47.0+rev1, RPi 4
* CLI v11.28.11 (npm install), macOS 10.14.6, balenaOS 2.46.1+rev1, RPi 3
* CLI v11.28.11 (npm install), macOS 10.14.6, balenaOS 2.47.0+rev1, RPi 4

https://forums.balena.io/t/no-logging-output-in-local-mode/65241/21

**Comment by sradevski** [comment] 2020-03-03 13:20
Another user reported having issues initially on a Pi2 and PiZero (not sure about the CLI version used then), but after installing the CLI using npm (version 11.28.8) it started working.

**Comment by pdcastro** [comment] 2020-03-04 00:53
Gathering more info from the users in [the forum thread](https://forums.balena.io/t/no-logging-output-in-local-mode/65241), it appears that the issue was with a broken CLI installation. In the investigation process, however, two other CLI issues were raised: #1646 and #1647 (the latter in relation to the fact that `balena logs` failed silently rather than noisily). Closing this issue in favour of those two.

**Closed by pdcastro** 2020-03-04 00:53 UTC
Labels: can't reproduce
