### ISSUE TITLE
balena join failed

### ISSUE THREAD

**Issue by slightcycle** [balena-io/balena-cli#1151] opened 2019-03-30 01:40 UTC
When I was using balena join xx.xx.xx.xx, I got this kind of error information :+1: 
"Command 'os-config join '"$(base64 -d <<< eyJhcHBsaWNhdGlvbk5hbWUiOiJteUFwcCIsImFwcGxpY2F0aW9uSWQiOjYsImRldmljZVR5cGUiOiJyYXNwYmVycnlwaTMiLCJ1c2VySWQiOjIsInVzZXJuYW1lIjoicm9vdCIsImFwcFVwZGF0ZVBvbGxJbnRlcnZhbCI6NjAwMDAwLCJsaXN0ZW5Qb3J0Ijo0ODQ4NCwidnBuUG9ydCI6NDQzLCJhcGlFbmRwb2ludCI6Imh0dHBzOi8vYXBpLm1pY3JvbGlmZWN5Y2xlLmNvbSIsInZwbkVuZHBvaW50IjoidnBuLm1pY3JvbGlmZWN5Y2xlLmNvbSIsInJlZ2lzdHJ5RW5kcG9pbnQiOiJyZWdpc3RyeS5taWNyb2xpZmVjeWNsZS5jb20iLCJkZWx0YUVuZHBvaW50IjoiaHR0cHM6Ly9kZWx0YS5taWNyb2xpZmVjeWNsZS5jb20iLCJwdWJudWJTdWJzY3JpYmVLZXkiOiIiLCJwdWJudWJQdWJsaXNoS2V5IjoiIiwibWl4cGFuZWxUb2tlbiI6Il9fdW51c2VkX18iLCJiYWxlbmFSb290Q0EiOiJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VaVmVrTkRRWHAxWjBGM1NVSkJaMGxLUVUxdE5VaDRUMEZFWmpCeFRVRXdSME5UY1VkVFNXSXpSRkZGUWtOM1ZVRk5RMEY0U0dwQlkwSm5UbFlLUWtGTlRVWlhUbWhNYlRGd1dUTktkbUpIYkcxYVYwNDFXVEo0YkV4dFRuWmlWRUZsUm5jd2VFOVVRWHBOYW10M1RVUkplRTFxUm1GR2R6QjVUMVJCZWdwTmFsbDNUVVJKZUUxcVJtRk5RMEY0U0dwQlkwSm5UbFpDUVUxTlJsZE9hRXh0TVhCWk0wcDJZa2RzYlZwWFRqVlpNbmhzVEcxT2RtSlVRME5CYVVsM0NrUlJXVXBMYjFwSmFIWmpUa0ZSUlVKQ1VVRkVaMmRKVUVGRVEwTkJaMjlEWjJkSlFrRkxUazFMUWtSNlZtNUxUMEZwUkhadFdUQTNNMVpuVkM5a1ZtZ0thVTB3YmtSUmN6RnBTazkyUWpRck9EQTJabEIyVEV4UlNrbFdhVFYwYnpkME1UaHVTRGhSTUVaYU1GQk1aemhWVTJkU1RHaDBVMmt5TlhoaGRFOXJUUXAyVmtKSWRXUjNTRmgzYmk4NFVXNUlMMVJNV0dFclpIQmhiSEJyVXl0VlYyRkhSa2hGVm10dFJGUnFZMGxNWlU1cE5TdFVTM0pGVEdaTldWSjNVamw0Q2xZMEswVmtiMDh5U3pkTVIwWmhXWEZVT0VFeFZDOUtkMGR0YzA5R1FqUlpjRlpqVG5RNWJrZ3hTbXhLYzFKWGVuVnhSSEZITTNwVFVIcHhjRmwyVkdzS05WTXdWek5sY3pWMGNqVkVhM2xYVmsxbmVFaHdSRlpVTTNoa2VqbFJWR016TTNsMk5sRmpWWGhaZFVWVlZ5ODRaREJGV21kak9FOXNia3BzU2xSclNncGFVblJVTW0xb1VGTlpjSGx0TUhobWVESjVlV2g2Wm5WdGNYZEZlbXRtTjFOVU16VjVSRzlZUnpBeGMyTmhVRUZyYm5ka0t6TlVWR1pDUVdoaWN6TmxDbTFyV2twNlJETTVjV1ozY201VlEweElhMjltUlVWWWJubGljMGt2WmpCTVdWazRRMDByWkdsR2RXbElWV2R6Y1VvNFpHNXpiRVkxY1hkVVZuVlJWVzhLWWtKdU1qSk9lak5LVW5GcWVTODBTVkYxZWxkaVJWVkphR1I1VmpWWVZWcEhjRE55TlU5RVVITmlhVWhPVlcwM2NYUlJjMmhMUVU5R0x6bFBaR1JtVGdwVFRrbFhXV0pzZUdSUFZ6ZEhVVGhVTlVST1YwcG5LMmhxVXk5bVlVbG5RMnNyWkRWSk9XRjZNekF4WjFaaU16ZEtVRGhwTXpkWWRXcDRXRE5qUkdKTUNsQkpiMjFCUjNsMGJETktXVE0yYUdjck9UQklUSG80YjJoT1FYUnNiemRLWlhkUFZsTkpZbEZMUjJkRGJISnJNRE5xYTNjd04yUndWMG95TjNreFRXTUtNMmN2SzJvNVMzUm9UM05pTW0xNWFqaHZhSEJWVkhvM2JVbFlRVkZVWmxCbFYyUkVRVTl6VFdsdWRHTkdia0ZzVTAxc1IzcFdVMDVSTkUwdlFteHdjd3B1TkhKbVMydFBhbEZ5U1dwNVZUWjBRV2ROUWtGQlIycG5XVGgzWjFsM2QwaFJXVVJXVWpCUFFrSlpSVVpKZUZZNFpTdExNSGRJYUZZMVFXUkxaMHhTQ21wcVRVVkxUMGR5VFVaQlIwRXhWV1JKZDFKS1RVVmxRVVpKZUZZNFpTdExNSGRJYUZZMVFXUkxaMHhTYW1wTlJVdFBSM0p2VTFOclNXcEJaMDFTTkhjS1NFRlpSRlpSVVVSRVFsWnFXVk0xZEdGWFRubGlNbmh3V20xV2FtVlhUbk5hVXpWcVlqSXlRME5SUkVwMVVqaFVaMEV6T1V0cVFVMUNaMDVXU0ZKTlJRcENWRUZFUVZGSUwwMUJjMGRCTVZWa1JIZFJSVUYzU1VKQ2FrRk9RbWRyY1docmFVYzVkekJDUVZGelJrRkJUME5CWjBWQlpsUlJUelJXTm5WVE1HNHhDakoxYlRGRWNGSnNOR2ROU1VKeFdVRnpSMElyVEZwblV6aFBTSFJSTWs1bVJuVkhUbFUxSzA5S05TdFFTMFZ2Wm1kUGIySk9kMk5MUTFCWFQzSTNTRGdLVWxONlRrcFhPRmsxVkROQk1VUklZMUEyWlVZclZIRXJTMUp4YTNwMWVEZzJPRWN5VUZSa2FXMVJWMmRtZW10dVREYzBlak1yWlRSRVpTdDNZMUp2YmdwM1lUSnRUakJGVGxveVozSnZlVmgzZEdOMlNYZEdSWE5QTjNkUlVrZ3pXVzlQUmpWdGIyNXBNMEUyVTJWeGFrUnJZbTV3YkVWMWVHbEpTVWczU0VkM0NtOHdMMDAxVmtaNlZFRmhjMlJ5WVUxelVFZEZUMlE0YlhWTlYyZzFVM2RWYUZSaU0xUkZhVVZ4YVdKWGFuRTNjbWN2SzBoYU0wUXlVbWhKVGtsak1EWUtZVGhKVFROSFRWRnRWRWgzV0U1eWNHZFFXa3hUU1hvMVVtUTJOVFp1UzNNclRIVjZhSFJHYkVWcVIxSkxhRmRIUlc1UmJUbHViM2RSTm1RdlVESk9TQXBNUzNsQ00zcHNhREY1VEVOVk5razBaa3MzYUZORlpuZFJaVVpUVkZaSGJuUlZSSE5HZDJGS2F6VXJOWFYxVVhndllVaFRPVVpUWTFFeVIyRkNhV0ZtQ2paeWJUY3lOREIwWXpOMlZtOVZkMHhpVDNZM1dGSmlZMjFPVlRkV1IwZGtObnB6UVM5NlIzVjFWbXBFV0RrMFpFbHVRek51YTIxeldGcFRWRlk0YWxBS2JrdEtWMVV5Tm5RNVkxRXdXVXg0ZDNOTVRVTndUbmhQWXpkdFV6TXlRVTQyY210VVFUaGpZblZwY21sQk5UVk5UVVpHYzJNeFVsSXdkazV5ZFhWNlRRcDZRalpZYWpCRFkxZElRbVF2TUc0M2MzWlZiMmN2Tm14bmJXbDNTRkJEVXpZMGRVRmtSMmRMTjIxWU4zUklZbEJ5YTBGMFdYTktTMHM0SzI1NFFrNUxDbTkwVDA5MWMyOVVVMHBaV0hKUmVsUkVWVEJ3V1RSQlptOHdkVmMyYVdwUVIwaDZaMEV2UTJGMloxbGlkRnBWZG1ZdlQxcEdPVkpPVVhGSVJHWm1NamtLVTFsT1JHUlhaM1ZaV0dKUldHUktkWFZRTUZkSVRFOXBXRkJhYWsweFl6MEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0iLCJhcGlLZXkiOiJYWFRLeDB1N2h5OHJXWTNFRkpRY2pBYTFYYUFjWW1QVyJ9)"'' failed with error: 4".

**Comment by pdcastro** [comment] 2019-04-02 13:05
@slightcycle, thanks for reporting this issue. We suspect that the error happened in the execution of `/usr/bin/os-config` on the device. The CLI currently only captures the exit error code ("failed with error: 4"), but if you tried running the `os-config` command manually on the device, hopefully you would see more information about the error.

So if you can, please try opening a terminal (ssh) on the device (the target device of the `balena join`) and run the command:
```
os-config join "$(base64 -d <<< eyJhcHBsaWNhdGlvbk5hbWUiOiJteUFwcCIsImFwcGxpY2F0aW9uSWQiOjYsImRldmljZVR5cGUiOiJyYXNwYmVycnlwaTMiLCJ1c2VySWQiOjIsInVzZXJuYW1lIjoicm9vdCIsImFwcFVwZGF0ZVBvbGxJbnRlcnZhbCI6NjAwMDAwLCJsaXN0ZW5Qb3J0Ijo0ODQ4NCwidnBuUG9ydCI6NDQzLCJhcGlFbmRwb2ludCI6Imh0dHBzOi8vYXBpLm1pY3JvbGlmZWN5Y2xlLmNvbSIsInZwbkVuZHBvaW50IjoidnBuLm1pY3JvbGlmZWN5Y2xlLmNvbSIsInJlZ2lzdHJ5RW5kcG9pbnQiOiJyZWdpc3RyeS5taWNyb2xpZmVjeWNsZS5jb20iLCJkZWx0YUVuZHBvaW50IjoiaHR0cHM6Ly9kZWx0YS5taWNyb2xpZmVjeWNsZS5jb20iLCJwdWJudWJTdWJzY3JpYmVLZXkiOiIiLCJwdWJudWJQdWJsaXNoS2V5IjoiIiwibWl4cGFuZWxUb2tlbiI6Il9fdW51c2VkX18iLCJiYWxlbmFSb290Q0EiOiJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VaVmVrTkRRWHAxWjBGM1NVSkJaMGxLUVUxdE5VaDRUMEZFWmpCeFRVRXdSME5UY1VkVFNXSXpSRkZGUWtOM1ZVRk5RMEY0U0dwQlkwSm5UbFlLUWtGTlRVWlhUbWhNYlRGd1dUTktkbUpIYkcxYVYwNDFXVEo0YkV4dFRuWmlWRUZsUm5jd2VFOVVRWHBOYW10M1RVUkplRTFxUm1GR2R6QjVUMVJCZWdwTmFsbDNUVVJKZUUxcVJtRk5RMEY0U0dwQlkwSm5UbFpDUVUxTlJsZE9hRXh0TVhCWk0wcDJZa2RzYlZwWFRqVlpNbmhzVEcxT2RtSlVRME5CYVVsM0NrUlJXVXBMYjFwSmFIWmpUa0ZSUlVKQ1VVRkVaMmRKVUVGRVEwTkJaMjlEWjJkSlFrRkxUazFMUWtSNlZtNUxUMEZwUkhadFdUQTNNMVpuVkM5a1ZtZ0thVTB3YmtSUmN6RnBTazkyUWpRck9EQTJabEIyVEV4UlNrbFdhVFYwYnpkME1UaHVTRGhSTUVaYU1GQk1aemhWVTJkU1RHaDBVMmt5TlhoaGRFOXJUUXAyVmtKSWRXUjNTRmgzYmk4NFVXNUlMMVJNV0dFclpIQmhiSEJyVXl0VlYyRkhSa2hGVm10dFJGUnFZMGxNWlU1cE5TdFVTM0pGVEdaTldWSjNVamw0Q2xZMEswVmtiMDh5U3pkTVIwWmhXWEZVT0VFeFZDOUtkMGR0YzA5R1FqUlpjRlpqVG5RNWJrZ3hTbXhLYzFKWGVuVnhSSEZITTNwVFVIcHhjRmwyVkdzS05WTXdWek5sY3pWMGNqVkVhM2xYVmsxbmVFaHdSRlpVTTNoa2VqbFJWR016TTNsMk5sRmpWWGhaZFVWVlZ5ODRaREJGV21kak9FOXNia3BzU2xSclNncGFVblJVTW0xb1VGTlpjSGx0TUhobWVESjVlV2g2Wm5WdGNYZEZlbXRtTjFOVU16VjVSRzlZUnpBeGMyTmhVRUZyYm5ka0t6TlVWR1pDUVdoaWN6TmxDbTFyV2twNlJETTVjV1ozY201VlEweElhMjltUlVWWWJubGljMGt2WmpCTVdWazRRMDByWkdsR2RXbElWV2R6Y1VvNFpHNXpiRVkxY1hkVVZuVlJWVzhLWWtKdU1qSk9lak5LVW5GcWVTODBTVkYxZWxkaVJWVkphR1I1VmpWWVZWcEhjRE55TlU5RVVITmlhVWhPVlcwM2NYUlJjMmhMUVU5R0x6bFBaR1JtVGdwVFRrbFhXV0pzZUdSUFZ6ZEhVVGhVTlVST1YwcG5LMmhxVXk5bVlVbG5RMnNyWkRWSk9XRjZNekF4WjFaaU16ZEtVRGhwTXpkWWRXcDRXRE5qUkdKTUNsQkpiMjFCUjNsMGJETktXVE0yYUdjck9UQklUSG80YjJoT1FYUnNiemRLWlhkUFZsTkpZbEZMUjJkRGJISnJNRE5xYTNjd04yUndWMG95TjNreFRXTUtNMmN2SzJvNVMzUm9UM05pTW0xNWFqaHZhSEJWVkhvM2JVbFlRVkZVWmxCbFYyUkVRVTl6VFdsdWRHTkdia0ZzVTAxc1IzcFdVMDVSTkUwdlFteHdjd3B1TkhKbVMydFBhbEZ5U1dwNVZUWjBRV2ROUWtGQlIycG5XVGgzWjFsM2QwaFJXVVJXVWpCUFFrSlpSVVpKZUZZNFpTdExNSGRJYUZZMVFXUkxaMHhTQ21wcVRVVkxUMGR5VFVaQlIwRXhWV1JKZDFKS1RVVmxRVVpKZUZZNFpTdExNSGRJYUZZMVFXUkxaMHhTYW1wTlJVdFBSM0p2VTFOclNXcEJaMDFTTkhjS1NFRlpSRlpSVVVSRVFsWnFXVk0xZEdGWFRubGlNbmh3V20xV2FtVlhUbk5hVXpWcVlqSXlRME5SUkVwMVVqaFVaMEV6T1V0cVFVMUNaMDVXU0ZKTlJRcENWRUZFUVZGSUwwMUJjMGRCTVZWa1JIZFJSVUYzU1VKQ2FrRk9RbWRyY1docmFVYzVkekJDUVZGelJrRkJUME5CWjBWQlpsUlJUelJXTm5WVE1HNHhDakoxYlRGRWNGSnNOR2ROU1VKeFdVRnpSMElyVEZwblV6aFBTSFJSTWs1bVJuVkhUbFUxSzA5S05TdFFTMFZ2Wm1kUGIySk9kMk5MUTFCWFQzSTNTRGdLVWxONlRrcFhPRmsxVkROQk1VUklZMUEyWlVZclZIRXJTMUp4YTNwMWVEZzJPRWN5VUZSa2FXMVJWMmRtZW10dVREYzBlak1yWlRSRVpTdDNZMUp2YmdwM1lUSnRUakJGVGxveVozSnZlVmgzZEdOMlNYZEdSWE5QTjNkUlVrZ3pXVzlQUmpWdGIyNXBNMEUyVTJWeGFrUnJZbTV3YkVWMWVHbEpTVWczU0VkM0NtOHdMMDAxVmtaNlZFRmhjMlJ5WVUxelVFZEZUMlE0YlhWTlYyZzFVM2RWYUZSaU0xUkZhVVZ4YVdKWGFuRTNjbWN2SzBoYU0wUXlVbWhKVGtsak1EWUtZVGhKVFROSFRWRnRWRWgzV0U1eWNHZFFXa3hUU1hvMVVtUTJOVFp1UzNNclRIVjZhSFJHYkVWcVIxSkxhRmRIUlc1UmJUbHViM2RSTm1RdlVESk9TQXBNUzNsQ00zcHNhREY1VEVOVk5razBaa3MzYUZORlpuZFJaVVpUVkZaSGJuUlZSSE5HZDJGS2F6VXJOWFYxVVhndllVaFRPVVpUWTFFeVIyRkNhV0ZtQ2paeWJUY3lOREIwWXpOMlZtOVZkMHhpVDNZM1dGSmlZMjFPVlRkV1IwZGtObnB6UVM5NlIzVjFWbXBFV0RrMFpFbHVRek51YTIxeldGcFRWRlk0YWxBS2JrdEtWMVV5Tm5RNVkxRXdXVXg0ZDNOTVRVTndUbmhQWXpkdFV6TXlRVTQyY210VVFUaGpZblZwY21sQk5UVk5UVVpHYzJNeFVsSXdkazV5ZFhWNlRRcDZRalpZYWpCRFkxZElRbVF2TUc0M2MzWlZiMmN2Tm14bmJXbDNTRkJEVXpZMGRVRmtSMmRMTjIxWU4zUklZbEJ5YTBGMFdYTktTMHM0SzI1NFFrNUxDbTkwVDA5MWMyOVVVMHBaV0hKUmVsUkVWVEJ3V1RSQlptOHdkVmMyYVdwUVIwaDZaMEV2UTJGMloxbGlkRnBWZG1ZdlQxcEdPVkpPVVhGSVJHWm1NamtLVTFsT1JHUlhaM1ZaV0dKUldHUktkWFZRTUZkSVRFOXBXRkJhYWsweFl6MEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0iLCJhcGlLZXkiOiJYWFRLeDB1N2h5OHJXWTNFRkpRY2pBYTFYYUFjWW1QVyJ9)"
```
(This command is an extract of the error message you pasted in the issue description.)

It will probably fail again, but hopefully you will be able to see a more informative error than "4". :-)
Our informed guess is that the `os-config` command is trying to contact an openBalena server under your control, but let's see what you find by executing `os-config` manually.

CC: @majorz, @richbayliss

**Comment by kameshsampath** [comment] 2019-04-06 20:13
@pdcastro  am getting the same error in macOS with openbalena deployed with docker for mac . Any thing that we need to do to get it working ?

**Comment by kameshsampath** [comment] 2019-04-06 20:23
> Our informed guess is that the os-config command is failing to contact an openBalena server under your control

@pdcastro - when I tried running `os-config update` on the device it fails with name not getting resolved...

**Comment by pdcastro** [comment] 2019-04-06 20:28
@kameshsampath, it's an error generated by `os-config` rather than the CLI itself, so what I recommend is:
* Search and post a message in the openBalena forum, which is monitored by the openBalena team: https://forums.balena.io/c/open-balena
* If you believe you have found a bug in the `os-config` component, browse and/or raise an issue in the `os-config` own GitHub repository: https://github.com/balena-os/os-config/issues

Either way (even if you found a bug in `os-config`), getting in touch with the openBalena team through the [openBalena forum](https://forums.balena.io/c/open-balena) is your best bet.

**Comment by kameshsampath** [comment] 2019-04-06 20:32
thanks @pdcastro - I did already posted in forum https://forums.balena.io/t/openbalena-on-macos/5913. Since am totally new to this OS, I wish to make sure i do it right before an issue.

thanks for the help

**Comment by pdcastro** [comment] 2019-04-06 20:45
You are welcome @kameshsampath. I would have helped if I knew more about it but I don't :-)  Hopefully you'll get an answer soon (Monday?) in the forum.

**Comment by pdcastro** [comment] 2019-06-20 13:34
Related issues:
* [`balena join` does not capture log output of `os-config`](https://github.com/balena-io/balena-cli/issues/1317)
* [`balena join` does not run on production balenaOS images](https://github.com/balena-io/balena-cli/issues/1319)

**Comment by pdcastro** [comment] 2019-06-20 13:46
> I did run the os-config directly on the device and getting an error message as Error: Merging config.json failed caused by: Expected JSON object

@kameshsampath, revisiting this issue... I think two different errors were reported here:

* `os-config` error 4: "FetchConfiguration". This is the error originally reported by `balena join`. We believe it means that `balena join` was unable to contact one of the openBalena servers, e.g. a network reachability issue. Decoding the base64 string of the original error report, the JSON object contains a few endpoints. Double check that they are all reachable by the device:
```
{ "apiEndpoint": "https://api.microlifecycle.com",
  "vpnEndpoint": "vpn.microlifecycle.com",
  "registryEndpoint": "registry.microlifecycle.com",
  "deltaEndpoint": "https://delta.microlifecycle.com",
```

* `os-config` error 11: _"Error: Merging config.json failed caused by: Expected JSON object"_ (when `os-config` was manually executed on the device). I am guessing that this may be an error escaping the JSON object on a shell command line. Perhaps add a "backlsashed single quote" before and after the base64 subshell, as follows:
```
os-config join \'"$(base64 -d <<< eyJhcHBsaWNhdGlvbk5hbWUiOiJteUFwcCIsImFwcGxpY2F0aW9uSWQiOjYsImRldmljZVR5cGUiOiJyYXNwYmVycnlwaTMiLCJ1c2VySWQiOjIsInVzZXJuYW1lIjoicm9vdCIsImFwcFVwZGF0ZVBvbGxJbnRlcnZhbCI6NjAwMDAwLCJsaXN0ZW5Qb3J0Ijo0ODQ4NCwidnBuUG9ydCI6NDQzLCJhcGlFbmRwb2ludCI6Imh0dHBzOi8vYXBpLm1pY3JvbGlmZWN5Y2xlLmNvbSIsInZwbkVuZHBvaW50IjoidnBuLm1pY3JvbGlmZWN5Y2xlLmNvbSIsInJlZ2lzdHJ5RW5kcG9pbnQiOiJyZWdpc3RyeS5taWNyb2xpZmVjeWNsZS5jb20iLCJkZWx0YUVuZHBvaW50IjoiaHR0cHM6Ly9kZWx0YS5taWNyb2xpZmVjeWNsZS5jb20iLCJwdWJudWJTdWJzY3JpYmVLZXkiOiIiLCJwdWJudWJQdWJsaXNoS2V5IjoiIiwibWl4cGFuZWxUb2tlbiI6Il9fdW51c2VkX18iLCJiYWxlbmFSb290Q0EiOiJMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VaVmVrTkRRWHAxWjBGM1NVSkJaMGxLUVUxdE5VaDRUMEZFWmpCeFRVRXdSME5UY1VkVFNXSXpSRkZGUWtOM1ZVRk5RMEY0U0dwQlkwSm5UbFlLUWtGTlRVWlhUbWhNYlRGd1dUTktkbUpIYkcxYVYwNDFXVEo0YkV4dFRuWmlWRUZsUm5jd2VFOVVRWHBOYW10M1RVUkplRTFxUm1GR2R6QjVUMVJCZWdwTmFsbDNUVVJKZUUxcVJtRk5RMEY0U0dwQlkwSm5UbFpDUVUxTlJsZE9hRXh0TVhCWk0wcDJZa2RzYlZwWFRqVlpNbmhzVEcxT2RtSlVRME5CYVVsM0NrUlJXVXBMYjFwSmFIWmpUa0ZSUlVKQ1VVRkVaMmRKVUVGRVEwTkJaMjlEWjJkSlFrRkxUazFMUWtSNlZtNUxUMEZwUkhadFdUQTNNMVpuVkM5a1ZtZ0thVTB3YmtSUmN6RnBTazkyUWpRck9EQTJabEIyVEV4UlNrbFdhVFYwYnpkME1UaHVTRGhSTUVaYU1GQk1aemhWVTJkU1RHaDBVMmt5TlhoaGRFOXJUUXAyVmtKSWRXUjNTRmgzYmk4NFVXNUlMMVJNV0dFclpIQmhiSEJyVXl0VlYyRkhSa2hGVm10dFJGUnFZMGxNWlU1cE5TdFVTM0pGVEdaTldWSjNVamw0Q2xZMEswVmtiMDh5U3pkTVIwWmhXWEZVT0VFeFZDOUtkMGR0YzA5R1FqUlpjRlpqVG5RNWJrZ3hTbXhLYzFKWGVuVnhSSEZITTNwVFVIcHhjRmwyVkdzS05WTXdWek5sY3pWMGNqVkVhM2xYVmsxbmVFaHdSRlpVTTNoa2VqbFJWR016TTNsMk5sRmpWWGhaZFVWVlZ5ODRaREJGV21kak9FOXNia3BzU2xSclNncGFVblJVTW0xb1VGTlpjSGx0TUhobWVESjVlV2g2Wm5WdGNYZEZlbXRtTjFOVU16VjVSRzlZUnpBeGMyTmhVRUZyYm5ka0t6TlVWR1pDUVdoaWN6TmxDbTFyV2twNlJETTVjV1ozY201VlEweElhMjltUlVWWWJubGljMGt2WmpCTVdWazRRMDByWkdsR2RXbElWV2R6Y1VvNFpHNXpiRVkxY1hkVVZuVlJWVzhLWWtKdU1qSk9lak5LVW5GcWVTODBTVkYxZWxkaVJWVkphR1I1VmpWWVZWcEhjRE55TlU5RVVITmlhVWhPVlcwM2NYUlJjMmhMUVU5R0x6bFBaR1JtVGdwVFRrbFhXV0pzZUdSUFZ6ZEhVVGhVTlVST1YwcG5LMmhxVXk5bVlVbG5RMnNyWkRWSk9XRjZNekF4WjFaaU16ZEtVRGhwTXpkWWRXcDRXRE5qUkdKTUNsQkpiMjFCUjNsMGJETktXVE0yYUdjck9UQklUSG80YjJoT1FYUnNiemRLWlhkUFZsTkpZbEZMUjJkRGJISnJNRE5xYTNjd04yUndWMG95TjNreFRXTUtNMmN2SzJvNVMzUm9UM05pTW0xNWFqaHZhSEJWVkhvM2JVbFlRVkZVWmxCbFYyUkVRVTl6VFdsdWRHTkdia0ZzVTAxc1IzcFdVMDVSTkUwdlFteHdjd3B1TkhKbVMydFBhbEZ5U1dwNVZUWjBRV2ROUWtGQlIycG5XVGgzWjFsM2QwaFJXVVJXVWpCUFFrSlpSVVpKZUZZNFpTdExNSGRJYUZZMVFXUkxaMHhTQ21wcVRVVkxUMGR5VFVaQlIwRXhWV1JKZDFKS1RVVmxRVVpKZUZZNFpTdExNSGRJYUZZMVFXUkxaMHhTYW1wTlJVdFBSM0p2VTFOclNXcEJaMDFTTkhjS1NFRlpSRlpSVVVSRVFsWnFXVk0xZEdGWFRubGlNbmh3V20xV2FtVlhUbk5hVXpWcVlqSXlRME5SUkVwMVVqaFVaMEV6T1V0cVFVMUNaMDVXU0ZKTlJRcENWRUZFUVZGSUwwMUJjMGRCTVZWa1JIZFJSVUYzU1VKQ2FrRk9RbWRyY1docmFVYzVkekJDUVZGelJrRkJUME5CWjBWQlpsUlJUelJXTm5WVE1HNHhDakoxYlRGRWNGSnNOR2ROU1VKeFdVRnpSMElyVEZwblV6aFBTSFJSTWs1bVJuVkhUbFUxSzA5S05TdFFTMFZ2Wm1kUGIySk9kMk5MUTFCWFQzSTNTRGdLVWxONlRrcFhPRmsxVkROQk1VUklZMUEyWlVZclZIRXJTMUp4YTNwMWVEZzJPRWN5VUZSa2FXMVJWMmRtZW10dVREYzBlak1yWlRSRVpTdDNZMUp2YmdwM1lUSnRUakJGVGxveVozSnZlVmgzZEdOMlNYZEdSWE5QTjNkUlVrZ3pXVzlQUmpWdGIyNXBNMEUyVTJWeGFrUnJZbTV3YkVWMWVHbEpTVWczU0VkM0NtOHdMMDAxVmtaNlZFRmhjMlJ5WVUxelVFZEZUMlE0YlhWTlYyZzFVM2RWYUZSaU0xUkZhVVZ4YVdKWGFuRTNjbWN2SzBoYU0wUXlVbWhKVGtsak1EWUtZVGhKVFROSFRWRnRWRWgzV0U1eWNHZFFXa3hUU1hvMVVtUTJOVFp1UzNNclRIVjZhSFJHYkVWcVIxSkxhRmRIUlc1UmJUbHViM2RSTm1RdlVESk9TQXBNUzNsQ00zcHNhREY1VEVOVk5razBaa3MzYUZORlpuZFJaVVpUVkZaSGJuUlZSSE5HZDJGS2F6VXJOWFYxVVhndllVaFRPVVpUWTFFeVIyRkNhV0ZtQ2paeWJUY3lOREIwWXpOMlZtOVZkMHhpVDNZM1dGSmlZMjFPVlRkV1IwZGtObnB6UVM5NlIzVjFWbXBFV0RrMFpFbHVRek51YTIxeldGcFRWRlk0YWxBS2JrdEtWMVV5Tm5RNVkxRXdXVXg0ZDNOTVRVTndUbmhQWXpkdFV6TXlRVTQyY210VVFUaGpZblZwY21sQk5UVk5UVVpHYzJNeFVsSXdkazV5ZFhWNlRRcDZRalpZYWpCRFkxZElRbVF2TUc0M2MzWlZiMmN2Tm14bmJXbDNTRkJEVXpZMGRVRmtSMmRMTjIxWU4zUklZbEJ5YTBGMFdYTktTMHM0SzI1NFFrNUxDbTkwVDA5MWMyOVVVMHBaV0hKUmVsUkVWVEJ3V1RSQlptOHdkVmMyYVdwUVIwaDZaMEV2UTJGMloxbGlkRnBWZG1ZdlQxcEdPVkpPVVhGSVJHWm1NamtLVTFsT1JHUlhaM1ZaV0dKUldHUktkWFZRTUZkSVRFOXBXRkJhYWsweFl6MEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0iLCJhcGlLZXkiOiJYWFRLeDB1N2h5OHJXWTNFRkpRY2pBYTFYYUFjWW1QVyJ9)"\'
```

**Comment by pdcastro** [comment] 2019-11-22 22:04
Closing this issue as it appears to be a troubleshooting matter, as discussed above, rather than a CLI bug actionable in the `balena-cli` repo. Feel free to reply though -- I can reopen the issue as needed.

**Closed by pdcastro** 2019-11-22 22:04 UTC
Labels: support
