### ISSUE TITLE
CLI does not install on arm64

### ISSUE THREAD

**Issue by joshughes** [balena-io/balena-cli#845] opened 2018-04-04 11:19 UTC
- **resin-cli version:**
Latest
- **Operating system and architecture:**
Debian Stretch node 8

```
FROM arm64v8/node:8-stretch

RUN apt-get update && apt-get install -y build-essential libconfig-dev
RUN npm install resin-cli -g --production --unsafe-perm

CMD ['/usr/local/bin/resin']
```

I have an arm64 build environment to create arm64 build containers. I would like to have the resin-cli tool available there but it fails to install. 

```

> ext2fs@0.1.1 install /usr/local/lib/node_modules/resin-cli/node_modules/ext2fs
> node-pre-gyp install --fallback-to-build

[91mnode-pre-gyp [0m[91mERR![0m[91m [0m[91mTried to download(404): https://github.com/resin-io/node-ext2fs/releases/download/v0.1.1/bindings-v0.1.1-node-v57-linux-arm64.tar.gz[0m[91m 
[0m[91mnode-pre-gyp [0m[91mERR! [0m[91mPre-built binaries not found for ext2fs@0.1.1 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
[0mmake: Entering directory '/usr/local/lib/node_modules/resin-cli/node_modules/ext2fs/build'
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/alloc.o
[91m../deps/e2fsprogs/lib/ext2fs/alloc.c:12:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
[0mext2fs.target.mk:177: recipe for target 'Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/alloc.o' failed
make: Leaving directory '/usr/local/lib/node_modules/resin-cli/node_modules/ext2fs/build'
```

**Comment by pimterry** [comment] 2018-04-05 10:41
That's true, but I'm afraid I don't have an nice fix for you.

Right now, we don't have an easy way to publish prebuilt binaries for ARM64 (which is what you'd need for ext2fs, and likely a few other submodules), so you'll need to build them yourself. Our [travis config](https://github.com/resin-io/node-ext2fs/blob/master/.travis.yml) might be useful to see the environment we're building in for x64. If you can build all of those yourself, the CLI should start working nicely (and I'd love to hear updates about progress there, in case any other users need this).

Long term we're actually intending to move away from npm entirely to use [standalone](https://github.com/resin-io/resin-cli#standalone-install) builds instead. That'll avoid this ext2fs problem entirely, but we currently only build those packages for x64 (using [pkg](https://github.com/zeit/pkg/)). I'd definitely be open to suggestions on widening that, but I'm not sure how good the cross-compiling support is there, and I don't think we're going to get to this in the short-term.

**Comment by joshughes** [comment] 2018-04-05 13:06
@pimterry Using Resin's own tooling you can cross-compile inside a docker container using qemu. It is slow of course but basically gives you emulation on anything that runs inside that container. 

https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Comment by pimterry** [comment] 2018-04-05 13:33
I haven't tested how pkg behaves on ARM, emulated or otherwise, and even if it does we'd need a nice way to get this running in CI without it becoming excruciatingly slow. There is almost certainly a route through here eventually, it's just not one we've investigated yet.

**Comment by pimterry** [comment] 2018-04-05 14:43
@joshughes could you tell me any more about the use case for this, and why you need the CLI in your container?

**Comment by joshughes** [comment] 2018-04-06 00:32
I have a CI pipeline where I need to run the CLI to upload a container image to resin with `resin deploy`

Since its an ARM image I run CI steps on the ARM server... I would be nice to also be able to do a `resin deploy` from the same ARM box... rather I have to upload it to my registry... then run another step on an x86 build server to download the image and then sync it to Resin. 

For the time being, I am just compiling my image on a x86 machine using the resin qemu toolchain. As you identified this is slower than it could be if I could just use my arm64 infrastructure for the entire pipeline. 

Anyway, I have ways to get around it, it just seemed to me like a use case worth considering as more people I imagine will want to utilize their own build systems to create images vs relying totally on Resin.

**Comment by zvin** [comment] 2019-01-28 16:43
@pdcastro since v1.0.26 node-ext2fs should build on arm.

**Comment by pdcastro** [comment] 2019-11-19 20:18
If this helps, I have not tested it myself but I see in issue #850 that a CLI user has been producing CLI Docker images that include ARM variants: https://hub.docker.com/r/samibourouis/balena-cli/tags

**Comment by ptrm** [comment] 2019-11-19 20:44
> @pdcastro since v1.0.26 ext2fs should build on arm.

> @pdcastro [...] a CLI user has been producing CLI Docker images that include ARM variants

As for working environments, after learning about ext2fs building on arm, I was able to `npm install resin-cli -g --production --unsafe-perm` in a chrooted Debian sid on Android 9 with [Termux](https://termux.com) : https://asciinema.org/a/hLhzU0y7PDMIRACjQaa5mPbPa
With enogh dev packages installed it should be reproducible, though I cannot recall the whole path (there was some building going on, but it went smoothly).

**Comment by b23prodtm** [comment] 2020-01-02 19:57
Installed on ubuntu-eoan for raspberry pi, you need to upgrade npm with the following cmd:

    RUN sudo npm  install -g npm 

Or added to the original call to install :

    RUN sudo npm install balena-cli -g --production --unsafe-perm npm

**Comment by pdcastro** [comment] 2020-03-04 00:37
Closing this issue with the understanding that it was resolved after the ext2fs module/dependency was upgraded, but also replacing it with issue #1647 [CLI on arm64: net-keepalive fails to compile, then "logs" and "live push" fail silently](https://github.com/balena-io/balena-cli/issues/1647).

Apart from the compilation of the `net-keepalive` module (#1647), I have had success with this issue's original "steps to reproduce" on a Raspberry Pi 4 device (arm64, `raspberrypi4-64` device type), running balena OS 2.47.0+rev1 (development image), with the device in [local mode](https://www.balena.io/docs/learn/develop/local-mode/):
```
# open ssh shell on the RPi 4, running balenaOS (64 bits)
$ ssh -p 22222 root@192.168.0.37
$ balena-engine run -it arm64v8/node:8-stretch /bin/bash
$ apt-get update && apt-get install -y build-essential libconfig-dev
$ npm install balena-cli -g --production --unsafe-perm
...
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi/build'
  SOLINK_MODULE(target) Release/obj.target/../node-addon-api/src/nothing.node
  COPY Release/nothing.node
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
In file included from ../deps/libffi/src/prep_cif.c:27:0:
../deps/libffi/include/ffi_common.h:17:23: fatal error: fficonfig.h: No such file or directory
 #include <fficonfig.h>
                       ^
compilation terminated.
deps/libffi/ffi.target.mk:117: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.71
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
...
+ balena-cli@11.28.11
added 2243 packages from 1813 contributors in 400.841s
```

Note that despite the compilation error above (issue #1647 remains), the CLI installation succeeds.

I have also got the same result using the sample Dockerfile mentioned/linked in the CLI's installation documentation, [NPM installation section](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#npm-installation). It uses an Ubuntu Bionic (18.04) base image, instead of `arm64v8/node:8-stretch`.

**Closed by pdcastro** 2020-03-04 00:37 UTC
Labels: type:feature
