### ISSUE TITLE
Config injection failing when there's no /dev/diskX

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io/balena-cli#532] opened 2017-05-16 14:31 UTC
`resin config inject` errors with `"path must be a string"` and immediately exits, without displaying the drive selection prompt when there are no `/dev/diskX` devices.

Workaround: `resin config inject ... --drive /dev/sdc`

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1owz)

**Comment by pdcastro** [comment] 2019-11-20 12:27
I believe this issue was fixed in dependency modules, maybe more than a year ago. Testing it now on a Linux container (Debian 9) where `/dev/diskX` does not exist, I cannot reproduce the error: the drive selection prompt is displayed correctly. However if you find that it has not been fixed, feel free to add a comment and will reopen the issue and investigate it further. Thanks for reporting it.

**Closed by pdcastro** 2019-11-20 12:27 UTC
Labels: platform:linux, type:bug
