### ISSUE TITLE
'You have to specify an exact os version'

### ISSUE THREAD

**Issue by BorisBokmans** [balena-io/balena-cli#1007] opened 2018-10-31 15:23 UTC
Dear people,

I'm trying to provision a VM (WIN10 Enterprise LTSB) to the Balena dashboard.
I installed the standalone Balena-CLI on the VM.
After specifying my hardware (I chose Intel NUC because of the VM usage) it started to download the DeviceOS image. This had success.
After that I received an error: 'You have to specify an exact os version'.

Somebody knows a fix for this?

Thanks!

https://ibb.co/ddBVdL

- **Cli version:**
- **Operating system and architecture:**

**Comment by pimterry** [comment] 2018-11-01 13:56
Hi @BorisBokmans thanks for the report, that definitely sounds like a bug! We'll take a look at it now, watch this space.

**Comment by pimterry** [comment] 2018-11-05 15:19
Just to keep you updated @BorisBokmans: this is caused by changes in CLI v9.0.0 to make a `version` argument required when configuring images (which quickstart does for you, under the hood). We're fixing this, but doing it properly is part of some larger changes to how version detection works in configuration, so it'll take a little longer.

In the meantime, you can either:

* Temporarily downgrade to a CLI version before v9 (note that before v9 the npm package was called `resin-cli`, not `balena-cli`)
* Run the setup commands for your device manually, instead of via quickstart:
	- Download a fresh OS: `balena os download intel-nuc --output <path> --version <version>` (the latest version for the NUC is `v2.13.6`)
	- Configure it for your app: `balena os configure <path> --application <appname> --version <version>`
	- Write it to disk: `balena os initialize <path> --type intel-nuc` (since you're setting up a VM, there may be a different step required to create a bootable VM image, that'll depend on the VM software you're using)

I'll update this ticket once we've resolved this more permanently, but hopefully one of the workarounds above will work for you in the meantime.

**Comment by pimterry** [comment] 2018-11-16 15:01
Just an update: this should be fully fixed by #1012, once that's merged & released.

**Comment by dfunckt** [comment] 2018-11-21 12:39
@BorisBokmans, the PR Tim mentioned above has been merged and released as part of v9.2.2 -- can you please check whether it solves the issue?

**Comment by thgreasi** [comment] 2018-11-23 14:05
Hi we have identified the issue and working on a fix.
Thanks for bringing this up.

**Comment by srlowe** [comment] 2019-10-31 13:36
Closing as fixes have been merged.  Please re-open if you still encounter problems.

**Closed by srlowe** 2019-10-31 13:36 UTC
Labels: type:bug
