### ISSUE TITLE
balena push fails when "image" is used in conjunction with "build" in docker-compose

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/balena-cli#2394] opened 2021-11-25 16:29 UTC
# Expected Behavior

I should be able to `balena push` a multicontainer project, where the `docker-compose.yml` has services that specify both the `image` and `build` keywords. 
If you're wondering why you would want to do this, if you specify `image` as well as `build`, then Compose names the built image with the value found in `image`.

# Actual Behavior

The `balena push` command will pack, send and build the containers as expected, but once the images have finished building, it gets stuck in a loop, repeatedly printing:
```
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
```
and occasionally outputting something like:
```
[Logs]    [11/25/2021, 4:15:57 PM] Installing service 'livechat local_image_livechat:latest'
```

When I pull the supervisor logs from the running device I can see the supervisor failing to find the correct image:
```
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]   Scheduling another update attempt in 32000ms due to failure:  Error: Failed to apply state transition steps. (HTTP code 404) no such container - No such image: local_image_livechat:latest  Steps:["start"]
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]         at fn (/usr/src/app/dist/app.js:6:8594)
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]       at runMicrotasks (<anonymous>)
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]   Device state apply error Error: Failed to apply state transition steps. (HTTP code 404) no such container - No such image: local_image_livechat:latest  Steps:["start"]
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]         at fn (/usr/src/app/dist/app.js:6:8594)
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]       at runMicrotasks (<anonymous>)
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Nov 25 16:16:30 db0c73f balena-supervisor[3070]: [api]     GET /v2/state/status 200 - 26.868 ms
Nov 25 16:16:31 db0c73f balena
```

If I then run `balena images` on the device, I can see that there is a built image on the device using the same name I set in the `image` field in `docker-compose.yml`, but for some reason, the supervisor is not being instructed to use that image, instead hardcoding it to `local_image_$SERVICE_NAME`.

# Steps to Reproduce the Problem

I've created a repo to reproduce the problem, which you can see here https://github.com/LucianBuzzo/balena-cli-push-image-mvr:

1. [Clone the repo](https://github.com/LucianBuzzo/balena-cli-push-image-mvr)
1. Set up a device and put it in local mode
1. `balena push` the repo to the device

# Specifications

- **balena CLI version:** 12.48.4
- **Cloud backend: openBalena or balenaCloud?** balenaCloud
- **Operating system version:** Windows 10
- **32/64 bit OS and processor:** 64-bit operating system, x64-based AMD processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** e.g.  node v12.15.0 (npm v6.13.4)

**Comment by pdcastro** [comment] 2021-11-25 21:40
Sounds like a duplicate of #1874, which means that PR #2395 would fix two issues at once. :-)

**Comment by pdcastro** [comment] 2021-11-25 21:44
By the way, in #1874, it was also reported that _"The same thing seems to happen when `container_name` is in the compose file"_ -- mentioning this just in case you have an insight following your recent investigation, but that could of course be something unrelated to be fixed in some future PR.

**Comment by LucianBuzzo** [comment] 2021-11-26 10:18
@pdcastro Using `container_name` seems to have no effect at all when using local mode 🤔

**Closed** 2021-11-26 11:59 UTC
