### ISSUE TITLE
Investigate variable delay after `balena help`.

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1708] opened 2020-04-13 10:16 UTC
`balena help` is currently slow because is loads all command modules at runtime to extract usage information. We could / should instead do this at compile time, like we do for `cli.markdown` documentation. But perhaps differently from `cli.markdown`, the file did not have to be committed to the github repo, instead treated like the `build` folder and uploaded to the npm registry. (Maybe it could be generated in the `build` folder.)

**Comment by pdcastro** [comment] 2020-04-13 10:18
We could perhaps also remove mixpanel/amplitude events from `balena help`, so there's nothing to "hang" an immediate command exit.

**Comment by srlowe** [comment] 2020-09-09 09:38
@pdcastro I think this is no longer relevant?, as help seems quite fast now (I think it uses the oclif manifest, which caches this info).

**Comment by pdcastro** [comment] 2020-09-09 11:08
I think the olicf manifest plus the full CLI conversion to oclif made a good difference, yes! There is still this comment:
> We could perhaps also remove mixpanel/amplitude events from `balena help`, so there's nothing to "hang" an immediate command exit.

But it's also not a big deal. @srlowe, if you don't think that removing the mixpanel/amplitude event makes much of a difference, or if the effort doesn't justify it, feel free to close this issue.

**Comment by srlowe** [comment] 2020-09-09 11:21
@pdcastro Ah yes, we probably should.  I'll leave it open but change the name then.

**Comment by srlowe** [comment] 2020-09-09 13:07
@pdcastro I've tested, and mixpanel is not currently being called with `balena` `balena help` or `balena help devices`, so will close.

**Comment by pdcastro** [comment] 2020-09-09 13:09
> @pdcastro I've tested, and mixpanel is not currently being called with `balena` `balena help` or `balena help devices`, so will close.

Ha. OK. Then it's something else that hangs for half a second or so after the output of `balena help` is printed.

**Comment by srlowe** [comment] 2020-09-09 13:21
@pdcastro Yeah it seems to be quite intermittent - from no delay, to about half a second as you say.  I'll reopen this as an investigation task.

**Comment by srlowe** [comment] 2020-09-16 14:19
@pdcastro Is this still happening for you?  I don't get a delay now.

**Comment by pdcastro** [comment] 2020-09-16 14:32
@srlowe, indeed it is not happening right now. Would it be because some network endpoint is currently returning a response very quickly, whereas a few days ago it was taking longer? In which case, the investigation might be to find out which endpoint, perhaps add an artificial delay for testing purposes, and then decide whether there is a case for `unref`'ing the socket to allow the CLI to exit promptly. I mean something like this line of code:
https://github.com/balena-io/balena-cli/blob/v12.20.0/lib/auth/server.ts#L126

**Comment by srlowe** [comment] 2020-09-16 14:45
@pdcastro Right. I'm also seeing calls to `http://localhost:8001/setup` - not sure what that is.

**Comment by pdcastro** [comment] 2020-09-16 14:50
> I'm also seeing calls to http://localhost:8001/setup - not sure what that is.

@srlowe I don't recognize / remember this endpoint, and now we need to find out where it is coming from! E.g. in case it is from some dependency package.

**Comment by pdcastro** [comment] 2020-11-25 11:04
Renamed the title from "intermittent" to "variable" because intermittent means it does not always happen, whereas variable means it always happens, but varies in duration. In my experience for the past few months, it always happens, typically between 0.5s and 1s, occasionally less than 0.5s and occasionally a few seconds long.

**Comment by srlowe** [comment] 2020-11-26 13:03
I did some tests with analytics enabled/disabled, and the results seem to confirm that analytics are indeed the cause of this delay. `balena version` averages about 900ms with analytics, and about 300ms without.

**Comment by srlowe** [comment] 2021-11-30 13:25
Closing, since investigation suggests analytics are the source of the delay, and we have already optimised the analytics call as much as possible.

**Closed by srlowe** 2021-11-30 13:25 UTC
Labels: type:ux-enhancement
